import { getCommunicationPolicy } from '../config/communicationPolicies.js';
import { COMMUNICATION_TEMPLATE_CATALOG } from '../fixtures/communication-sample.js';
export const COMMUNICATION_ENGINE_VERSION='2.8.0';
const clone=v=>JSON.parse(JSON.stringify(v));
const fixedNow='2026-08-06T21:40:00.000Z';
function hash(value){const s=typeof value==='string'?value:JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).toUpperCase().padStart(8,'0');}
function replaceTokens(text,vars={}){return String(text||'').replace(/\{([^}]+)\}/g,(_,key)=>String(vars[key]??'—'));}
function dateKey(iso){return String(iso).slice(0,10);}
function hourUtc(iso){return new Date(iso).getUTCHours();}
function inQuietHours(iso,quiet){const h=hourUtc(iso);return quiet.start>quiet.end?(h>=quiet.start||h<quiet.end):(h>=quiet.start&&h<quiet.end);}
function nextAllowedAt(iso,quiet){const d=new Date(iso);const h=d.getUTCHours();if(!inQuietHours(iso,quiet))return iso;if(quiet.start>quiet.end&&h>=quiet.start)d.setUTCDate(d.getUTCDate()+1);d.setUTCHours(quiet.end,0,0,0);return d.toISOString();}
function purposeConsent(recipient,purpose){const key=`${purpose}Consent`;if(purpose==='service')return recipient.preferences.serviceConsent!==false;return recipient.preferences[key]===true;}
function externalSafe(message){const forbidden=['incluscore','score','dette','debt','montant approuvé','approved amount','religion','ethnie','ethnicity','political'];const body=`${message.subject||''} ${message.body||''}`.toLowerCase();return !forbidden.some(x=>body.includes(x));}
function summarize(w){const messages=w.messages||[];return{total:messages.length,inApp:messages.filter(x=>x.channel==='inApp').length,externalPrepared:messages.filter(x=>['sms','email'].includes(x.channel)).length,queued:messages.filter(x=>x.status==='queued').length,scheduled:messages.filter(x=>x.status==='scheduled').length,delivered:messages.filter(x=>x.status==='delivered').length,failed:messages.filter(x=>x.status==='failed').length,unread:messages.filter(x=>x.channel==='inApp'&&x.status==='delivered'&&!x.readAt).length,acknowledged:messages.filter(x=>x.acknowledgedAt).length,suppressed:(w.suppressionLog||[]).length};}
function externalCountForDay(messages,recipientId,at){return messages.filter(x=>x.recipientId===recipientId&&['sms','email'].includes(x.channel)&&dateKey(x.createdAt)===dateKey(at)&&x.status!=='suppressed').length;}
function latestExternal(messages,recipientId){return messages.filter(x=>x.recipientId===recipientId&&['sms','email'].includes(x.channel)&&x.status!=='suppressed').sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]||null;}
function minutesBetween(a,b){return Math.abs(new Date(a)-new Date(b))/60000;}
function createMessage({event,recipient,template,channel,policy,createdAt}){
  const lang=recipient.language==='en'?'en':'fr';const body=replaceTokens(template[channel]?.[lang]||template.inApp[lang],event.variables);const subject=replaceTokens(template.title[lang],event.variables);
  const id=`MSG-${hash([event.id,recipient.id,channel,event.dedupeKey])}`;
  const quiet=recipient.preferences.quietHours||policy.quietHours;const scheduledAt=channel==='inApp'?createdAt:nextAllowedAt(createdAt,quiet);const status=channel==='inApp'?'delivered':(scheduledAt===createdAt?'queued':'scheduled');
  return{id,eventId:event.id,dedupeKey:event.dedupeKey,templateId:event.templateId,templateVersion:'2.8.0',purpose:template.purpose,priority:template.priority,recipientId:recipient.id,recipientType:recipient.type,recipientName:recipient.name,language:lang,channel,subject,body,createdAt,scheduledAt,status,attempts:0,deliveryReceipt:null,readAt:null,acknowledgedAt:null,snoozedUntil:null,dataMinimised:channel==='inApp'||externalSafe({subject,body}),containsRawFinancialData:false,automaticDecisionContent:false,idempotencyKey:`COMM-${hash([event.dedupeKey,recipient.id,channel])}`};
}
export function createCommunicationWorkspace(input={},options={}){
  const policy=getCommunicationPolicy(options.policyId||'balanced');const at=options.createdAt||fixedNow;const recipients=clone(input.recipients||[]);const events=clone(input.events||[]);const messages=[];const suppressionLog=[];const seen=new Set();
  for(const event of events){
    const recipient=recipients.find(x=>x.id===event.recipientId);const template=COMMUNICATION_TEMPLATE_CATALOG[event.templateId];
    if(!recipient||!template){suppressionLog.push({eventId:event.id,reason:'recipient-or-template-missing',at});continue;}
    const dedupeSignature=`${event.dedupeKey}|${recipient.id}`;
    if(seen.has(dedupeSignature)){suppressionLog.push({eventId:event.id,recipientId:recipient.id,reason:'duplicate-within-window',at});continue;}seen.add(dedupeSignature);
    if(recipient.preferences.inApp&&policy.allowedChannels.includes('inApp'))messages.push(createMessage({event,recipient,template,channel:'inApp',policy,createdAt:event.createdAt||at}));
    const externalChannels=['sms','email'];
    for(const channel of externalChannels){
      if(!policy.allowedChannels.includes(channel)||recipient.preferences[channel]!==true)continue;
      const verified=channel==='sms'?recipient.contacts.phoneVerified:recipient.contacts.emailVerified;
      if(!verified){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'contact-not-verified',at});continue;}
      if(!purposeConsent(recipient,template.purpose)){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'purpose-consent-missing',at});continue;}
      if(externalCountForDay(messages,recipient.id,event.createdAt||at)>=policy.maxExternalMessagesPerRecipientPerDay){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'daily-rate-limit',at});continue;}
      const latest=latestExternal(messages,recipient.id);if(latest&&minutesBetween(latest.createdAt,event.createdAt||at)<policy.minimumExternalIntervalMinutes){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'minimum-interval',at});continue;}
      const msg=createMessage({event,recipient,template,channel,policy,createdAt:event.createdAt||at});
      if(channel==='sms'&&msg.body.length>policy.smsMaximumCharacters){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'sms-length-limit',at});continue;}
      if(!msg.dataMinimised){suppressionLog.push({eventId:event.id,recipientId:recipient.id,channel,reason:'external-sensitive-content',at});continue;}
      messages.push(msg);
    }
  }
  const w={engineVersion:COMMUNICATION_ENGINE_VERSION,workspaceId:`COMM-${hash([policy.version,recipients.map(x=>x.id),events.map(x=>x.id)])}`,policy:clone(policy),createdAt:at,recipients,events,messages,suppressionLog,deliveryLog:[],message:null,templates:Object.entries(COMMUNICATION_TEMPLATE_CATALOG).map(([id,x])=>({id,purpose:x.purpose,audience:x.audience,priority:x.priority,version:'2.8.0',languages:['fr','en'],channels:['inApp','sms','email']})),safeguards:{actualExternalSendingEnabled:false,automaticCreditDecisionAllowed:false,marketingWithoutConsentAllowed:false,rawFinancialDataInExternalMessageAllowed:false,quietHoursEnforced:true,deduplicationEnforced:true,rateLimitsEnforced:true,recipientOptOutRespected:true,humanEscalationRequired:true},limitations:['sms-and-email-delivery-are-simulated','production-requires-provider-connectors','contact-verification-is-synthetic-data','local-storage-is-not-a-production-message-vault']};w.summary=summarize(w);return w;
}
export function dispatchPreparedMessages(workspace,input={}){const w=clone(workspace);const at=input.at||'2026-08-07T07:05:00.000Z';for(const m of w.messages){if(!['queued','scheduled','retry'].includes(m.status)||new Date(m.scheduledAt)>new Date(at))continue;m.attempts+=1;if(m.attempts>w.policy.maximumRetries){m.status='failed';m.lastError='maximum-retries-reached';continue;}m.status='delivered';m.deliveredAt=at;m.deliveryReceipt={receiptId:`RCPT-${hash([m.id,at,m.attempts])}`,provider:'simulated-provider',status:'delivered'};w.deliveryLog.unshift({at,messageId:m.id,channel:m.channel,outcome:'delivered',simulated:true});}w.message={tone:'success',text:'prepared-messages-dispatched-in-simulation'};w.summary=summarize(w);return w;}
export function recordDeliveryOutcome(workspace,input={}){if(!input.messageId||!['delivered','failed','retry'].includes(input.outcome))throw new TypeError('message and supported outcome are required');const w=clone(workspace);const m=w.messages.find(x=>x.id===input.messageId);if(!m)throw new Error('message not found');m.attempts+=1;m.status=input.outcome;m.lastError=input.outcome==='failed'?String(input.reason||'simulated-provider-failure'):null;if(input.outcome==='delivered'){m.deliveredAt=input.at||fixedNow;m.deliveryReceipt={receiptId:`RCPT-${hash([m.id,input.at||fixedNow,m.attempts])}`,provider:'simulated-provider',status:'delivered'};}if(input.outcome==='retry')m.scheduledAt=input.retryAt||'2026-08-07T09:00:00.000Z';w.deliveryLog.unshift({at:input.at||fixedNow,messageId:m.id,channel:m.channel,outcome:input.outcome,reason:input.reason||null,simulated:true});w.summary=summarize(w);return w;}
export function markCommunicationRead(workspace,input={}){if(!input.messageId||!input.actor?.id)throw new TypeError('message and actor are required');const w=clone(workspace);const m=w.messages.find(x=>x.id===input.messageId);if(!m)throw new Error('message not found');if(m.channel!=='inApp')throw new Error('only in-app messages can be marked read');m.readAt=input.at||fixedNow;m.readBy=clone(input.actor);w.summary=summarize(w);return w;}
export function acknowledgeCommunication(workspace,input={}){if(!input.messageId||!input.actor?.id)throw new TypeError('message and actor are required');const w=clone(workspace);const m=w.messages.find(x=>x.id===input.messageId);if(!m)throw new Error('message not found');m.acknowledgedAt=input.at||fixedNow;m.acknowledgedBy=clone(input.actor);w.summary=summarize(w);return w;}
export function snoozeCommunication(workspace,input={}){if(!input.messageId||!input.actor?.id||Number(input.hours)<=0)throw new TypeError('message, actor and positive hours are required');const w=clone(workspace);const m=w.messages.find(x=>x.id===input.messageId);if(!m)throw new Error('message not found');const d=new Date(input.at||fixedNow);d.setUTCHours(d.getUTCHours()+Number(input.hours));m.snoozedUntil=d.toISOString();m.snoozedBy=clone(input.actor);w.summary=summarize(w);return w;}
export function updateRecipientPreference(workspace,input={}){if(!input.recipientId||!['inApp','sms','email'].includes(input.channel)||typeof input.enabled!=='boolean'||!input.actor?.id)throw new TypeError('recipient, channel, enabled and actor are required');const w=clone(workspace);const r=w.recipients.find(x=>x.id===input.recipientId);if(!r)throw new Error('recipient not found');r.preferences[input.channel]=input.enabled;w.deliveryLog.unshift({at:input.at||fixedNow,recipientId:r.id,action:'channel-preference-updated',channel:input.channel,enabled:input.enabled,actor:clone(input.actor)});w.summary=summarize(w);return w;}
export function validateCommunicationWorkspace(w){return Boolean(w?.engineVersion&&w?.policy?.version&&Array.isArray(w.messages)&&Array.isArray(w.suppressionLog)&&Array.isArray(w.recipients)&&w.safeguards?.actualExternalSendingEnabled===false&&w.safeguards?.automaticCreditDecisionAllowed===false&&w.safeguards?.rawFinancialDataInExternalMessageAllowed===false&&w.safeguards?.quietHoursEnforced===true&&w.messages.every(x=>x.id&&x.idempotencyKey&&x.dataMinimised===true));}
