export const DOCUMENT_INTELLIGENCE_ENGINE_VERSION='2.5.0';
const clone=v=>JSON.parse(JSON.stringify(v));
const round=(v,p=0)=>{const f=10**p;return Math.round(Number(v||0)*f)/f;};
const TYPES={identityDocument:['carte identite','identite','id-mali'],creditRequest:['demande credit','montant demandé','duree'],consentForm:['consentement','finalite','retrait possible'],activityEvidence:['attestation activite','visite','anciennete'],cashflowEvidence:['carnet ventes','mai:','juin:','juillet:'],debtStatement:['engagements','mensualite','dettes actives'],supplierReceipt:['recu fournisseur','reference: sup','montant:'],coopMembership:['registre cooperative','membres actifs','cotisations'],seasonalPlan:['plan campagne','semis','recolte','differe']};
function normalize(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function detectType(doc){const hay=normalize(`${doc.fileName} ${doc.content}`);let best={type:'other',hits:0};for(const [type,words] of Object.entries(TYPES)){const hits=words.filter(w=>hay.includes(normalize(w))).length;if(hits>best.hits)best={type,hits};}const declared=doc.declaredType;if(declared&&TYPES[declared]&&best.hits===0)best={type:declared,hits:1};return {...best,confidence:Math.min(99,55+best.hits*12+(best.type===declared?8:0))};}
function capture(content,re){const m=String(content||'').match(re);return m?String(m[1]).trim():null;}
function moneyValues(content){return [...String(content||'').matchAll(/(?:montant(?: demandé)?|mensualité déclarée|mai|juin|juillet)\s*:\s*([0-9\s]+)\s*FCFA/gi)].map(x=>Number(x[1].replace(/\s/g,''))).filter(Number.isFinite);}
export function classifyDocument(doc){if(!doc?.id||!doc?.content)throw new TypeError('document id and content are required');const d=detectType(doc);return {documentId:doc.id,detectedType:d.type,declaredType:doc.declaredType||null,classificationConfidence:d.confidence,classificationMatch:!doc.declaredType||doc.declaredType===d.type,hits:d.hits};}
export function extractDocumentFields(doc){const classification=classifyDocument(doc);const c=String(doc.content||'');const fields=[];const push=(key,value,confidence)=>{if(value!==null&&value!=='')fields.push({key,value,confidence:round(Math.min(Number(doc.quality||70),confidence)),sourceDocumentId:doc.id,requiresHumanValidation:true});};push('personName',capture(c,/(?:Nom|Demandeur|Titulaire|Client|Producteur)\s*:\s*([^|]+)/i),92);push('reference',capture(c,/(?:Référence)\s*:\s*([^|]+)/i),90);push('city',capture(c,/(?:Ville|Localité)\s*:\s*([^|]+)/i),86);push('date',capture(c,/(?:Date(?: émission| AG)?|Visite)\s*:\s*(\d{4}-\d{2}-\d{2})/i),95);push('durationMonths',capture(c,/(?:Durée|Différé demandé)\s*:\s*(\d+)\s*mois/i),90);const amounts=moneyValues(c);amounts.forEach((value,index)=>push(`amount${index+1}`,value,88));return {engineVersion:DOCUMENT_INTELLIGENCE_ENGINE_VERSION,documentId:doc.id,classification,fields,averageConfidence:fields.length?round(fields.reduce((s,x)=>s+x.confidence,0)/fields.length,1):0,rawDocumentPreserved:true,automaticTruthAllowed:false,humanValidationRequired:true};}
export function analyzeDocuments(documents=[]){const results=documents.map(doc=>({...clone(doc),analysis:extractDocumentFields(doc)}));return {engineVersion:DOCUMENT_INTELLIGENCE_ENGINE_VERSION,documentCount:results.length,results,averageExtractionConfidence:results.length?round(results.reduce((s,x)=>s+x.analysis.averageConfidence,0)/results.length,1):0,classificationMismatches:results.filter(x=>!x.analysis.classification.classificationMatch).map(x=>x.id),safeguards:{rawDocumentPreserved:true,automaticTruthAllowed:false,humanValidationRequired:true,externalAiRequired:false},limitations:['deterministic-demo-text-extraction','image-ocr-not-included-in-this-prototype','all-extracted-fields-require-human-validation']};}
