export const engines = [
  { id:'CORE', name:'CREDIPASS Core Engine', version:'4.0.0', status:'operational', block:1 },
  { id:'LANG', name:'Language Engine', version:'1.5.0', status:'operational', block:2 },
  { id:'ACCESS', name:'Accessibility Engine', version:'1.0.0', status:'operational', block:2 },
  { id:'EXPERIENCE', name:'Experience Engine', version:'1.5.0', status:'operational', block:3 },
  { id:'IDENTITY', name:'Identity & Access Engine', version:'1.0.0-demo', status:'prepared', block:4 },
  { id:'PROFILE', name:'Socio-Economic Profile Engine', version:'1.0.0', status:'operational', block:5 },
  { id:'EVIDENCE', name:'Financial Evidence Engine', version:'1.0.0', status:'operational', block:6 },
  { id:'CASHFLOW', name:'Cashflow Reconstruction Engine', version:'1.1.0', status:'operational', block:7 },
  { id:'CONFIDENCE', name:'Data Quality & Confidence Engine', version:'1.1.0', status:'operational', block:7 },
  { id:'INCLUSCORE', name:'INCLUSCORE Engine', version:'1.2.1', status:'operational', block:8 },
  { id:'HEALTH', name:'Financial Health Engine', version:'1.3.0', status:'operational', block:9 },
  { id:'DEBT', name:'Debt & Over-Indebtedness Engine', version:'1.3.0', status:'operational', block:9 },
  { id:'SIMULATION', name:'Responsible Credit Simulation Engine', version:'1.4.0', status:'operational', block:10 },
  { id:'SEASONAL', name:'Seasonal Finance Engine', version:'1.4.0', status:'operational', block:10 },
  { id:'POLICY', name:'Policy & Rules Engine', version:'1.5.0', status:'operational', block:11 },
  { id:'ORCHESTRATOR', name:'Recommendation Orchestrator', version:'1.5.0', status:'operational', block:11 },
  { id:'WORKFLOW', name:'Credit Workflow Engine', version:'1.6.0', status:'operational', block:12 },
  { id:'HUMAN_APPEAL', name:'Human Override & Appeal Engine', version:'1.6.0', status:'operational', block:12 },
  { id:'PASSPORT', name:'Financial Passport Engine', version:'1.7.0', status:'operational', block:13 },
  { id:'PROGRESSION', name:'Financial Progression Engine', version:'1.8.0', status:'operational', block:14 },
  { id:'DEMO_SCENARIO', name:'Demo & Scenario Engine', version:'3.1.0', status:'operational', block:15 },
  { id:'COOP_SCORE', name:'COOP-SCORE Engine', version:'2.0.0', status:'operational', block:16 },
  { id:'GROUP_FINANCING', name:'Group Financing Engine', version:'2.2.0', status:'operational', block:17 },
  { id:'EARLY_WARNING', name:'Early Warning Engine', version:'2.2.0', status:'operational', block:18 },
  { id:'POST_FINANCING', name:'Post-Financing Monitoring Engine', version:'2.2.0', status:'operational', block:18 },
  { id:'PORTFOLIO_RISK', name:'Portfolio Risk Engine', version:'2.4.0', status:'operational', block:19 },
  { id:'INSTITUTIONAL_PILOT', name:'Institutional Pilot & Client Readiness Engine', version:'2.3.0', status:'operational', block:20 },
  { id:'DOCUMENT_INTELLIGENCE', name:'Document Intelligence Engine', version:'2.5.0', status:'operational', block:21 },
  { id:'FINANCING_FILE', name:'Financing File Engine', version:'2.5.0', status:'operational', block:21 },
  { id:'TRUST_VERIFICATION', name:'Trust, Verification & Fraud Engine', version:'2.6.0', status:'operational', block:22 },
  { id:'OFFLINE_SYNC', name:'Offline & Synchronization Engine', version:'2.7.0', status:'operational', block:23 },
  { id:'FIELD_OPERATIONS', name:'Field Operations Engine', version:'2.7.0', status:'operational', block:23 },
  { id:'COMMUNICATION', name:'Communication & Notification Engine', version:'2.8.0', status:'operational', block:24 },
  { id:'REPORTING', name:'Reporting & Professional Document Engine', version:'2.9.0', status:'operational', block:25 },
  { id:'INSTITUTIONAL_CONNECTOR', name:'CREDIPASS CONNECT & Institutional Connector Engine', version:'3.0.0', status:'operational', block:26 },
  { id:'PRODUCT_MATCHING', name:'Product Matching Engine', version:'3.1.0', status:'operational', block:27 },
  { id:'FINANCIAL_LEARNING', name:'Financial Learning Engine', version:'3.1.0', status:'operational', block:27 },
  { id:'DIGITAL_VAULT', name:'Digital Vault Engine', version:'3.2.0', status:'operational', block:28 },
  { id:'CONSENT_PRIVACY', name:'Consent & Privacy Engine', version:'3.2.0', status:'operational', block:28 },
  { id:'INCLUSION_ANALYTICS', name:'Inclusion Observatory & Impact Analytics Engine', version:'3.3.0', status:'operational', block:29 },
  { id:'SECURITY', name:'Security Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'MODEL_GOVERNANCE', name:'Model Governance Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'MODEL_VALIDATION', name:'Model Validation Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'FAIRNESS_MONITORING', name:'Fairness Monitoring Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'TENANT_CONFIGURATION', name:'Tenant Configuration Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'REGIONAL_OPERATIONS', name:'Regional Operations Engine', version:'4.0.0', status:'operational', block:30 },
  { id:'PLATFORM_OPERATIONS', name:'Platform Operations Engine', version:'4.0.0', status:'operational', block:30 }
];