import { getFinancingFilePolicy, validateFinancingFilePolicy } from '../config/financingFilePolicies.js';
import { analyzeDocuments } from './documentIntelligenceEngine.js';
export const FINANCING_FILE_ENGINE_VERSION='2.5.0';
const clone=v=>JSON.parse(JSON.stringify(v));
const round=(v,p=0)=>{const f=10**p;return Math.round(Number(v||0)*f)/f;};
function reqTypes(data,policy){const types=[...policy.requiredBase];if(data.cooperativeProfile)types.push(...policy.conditional.cooperative);if(data.person?.activityKey==='rainfedAgriculture')types.push(...policy.conditional.agriculture);return [...new Set(types)];}
function expectedAmount(data){return Number(data.creditRequest?.amount||data.profile?.requestedAmount||0);}
export function buildFinancingFile(input,options={}){
 const {data,documents=[],quality,recommendation,policyEvaluation}=input||{};if(!data?.person)throw new TypeError('financing file requires applicant data');const policy=getFinancingFilePolicy(options.policyId||'balanced');if(!validateFinancingFilePolicy(policy))throw new TypeError('invalid financing file policy');
 const intelligence=analyzeDocuments(documents);const validated=new Set(options.validatedDocumentIds||[]);const rejected=new Set(options.rejectedDocumentIds||[]);const required=reqTypes(data,policy);const byType=new Map();for(const doc of intelligence.results){const type=doc.analysis.classification.detectedType;const arr=byType.get(type)||[];arr.push(doc);byType.set(type,arr);}
 const checklist=required.map(type=>{const docs=byType.get(type)||[];const usable=docs.filter(x=>!rejected.has(x.id));const valid=usable.filter(x=>validated.has(x.id)&&x.analysis.averageConfidence>=policy.minimumExtractionConfidence);return {type,required:true,documentIds:docs.map(x=>x.id),present:usable.length>0,validated:valid.length>0,status:valid.length?'validated':usable.length?'pending-human-validation':'missing'};});
 const contradictions=[];const requestDocs=byType.get('creditRequest')||[];for(const doc of requestDocs){for(const f of doc.analysis.fields.filter(x=>x.key.startsWith('amount'))){if(Number(f.value)>0&&Number(f.value)!==expectedAmount(data))contradictions.push({id:`AMOUNT-${doc.id}`,severity:'blocking',documentId:doc.id,field:'requestedAmount',expected:expectedAmount(data),extracted:Number(f.value),message:'requested-amount-mismatch',humanResolutionRequired:true});}}
 const nameExpected=String(data.person.name||'').trim().toLowerCase();for(const doc of intelligence.results){const f=doc.analysis.fields.find(x=>x.key==='personName');if(f&&String(f.value).trim().toLowerCase()!==nameExpected)contradictions.push({id:`NAME-${doc.id}`,severity:'blocking',documentId:doc.id,field:'personName',expected:data.person.name,extracted:f.value,message:'applicant-name-mismatch',humanResolutionRequired:true});}
 const present=checklist.filter(x=>x.present).length, validatedCount=checklist.filter(x=>x.validated).length;const rawCompleteness=round((present/required.length)*100,1), validatedCompleteness=round((validatedCount/required.length)*100,1);const blocking=contradictions.filter(x=>x.severity==='blocking'&&!rejected.has(x.documentId));const averageConfidence=intelligence.averageExtractionConfidence;
 const ready=present===required.length&&validatedCompleteness>=policy.minimumValidatedCompleteness&&blocking.length<=policy.maximumBlockingContradictions&&averageConfidence>=policy.minimumExtractionConfidence;
 return {engineVersion:FINANCING_FILE_ENGINE_VERSION,status:ready?'ready-for-human-committee':'in-preparation',fileId:`FILE-${data.scenarioId||'baseline'}-${policy.id}`.toUpperCase(),applicant:{name:data.person.name,city:data.person.city,activityKey:data.person.activityKey},policy,documents:intelligence.results.map(doc=>({...doc,humanStatus:rejected.has(doc.id)?'rejected':validated.has(doc.id)?'validated':'pending-human-validation'})),checklist,summary:{requiredCount:required.length,presentCount:present,validatedCount,rawCompleteness,validatedCompleteness,averageExtractionConfidence:averageConfidence,blockingContradictions:blocking.length,pendingHumanValidation:intelligence.results.filter(x=>!validated.has(x.id)&&!rejected.has(x.id)).length,committeeReady:ready},contradictions,missingTypes:checklist.filter(x=>!x.present).map(x=>x.type),pendingTypes:checklist.filter(x=>x.present&&!x.validated).map(x=>x.type),committeePack:{applicant:data.person.name,requestedAmount:expectedAmount(data),recommendationCode:recommendation?.recommendationCode||null,policyRulesPassed:policyEvaluation?.summary?.passed||0,documentReferences:intelligence.results.filter(x=>validated.has(x.id)&&!rejected.has(x.id)).map(x=>x.id),generated:false,requiresHumanDecision:true},safeguards:{extractionDoesNotCreateTruth:true,rawDocumentsRemainAuthoritative:true,humanValidationRequired:true,automaticCreditDecisionAllowed:false,rejectedDocumentsRemainAuditable:true,consentRequired:true},excludedData:['ethnicity','religion','political-opinion','private-messages','phone-contacts','social-media-behaviour'],limitations:[...intelligence.limitations,'institution-specific-document-requirements-require-pilot-validation'],trace:{deterministic:true,calculatedAt:options.calculatedAt||'2026-08-06T20:50:00.000Z',policyVersion:policy.version,documentIds:intelligence.results.map(x=>x.id)}};
}
export function validateFinancingFileResult(r){return Boolean(r?.engineVersion&&r?.policy?.version&&r?.summary&&r.summary.rawCompleteness>=0&&r.summary.rawCompleteness<=100&&r.summary.validatedCompleteness>=0&&r.summary.validatedCompleteness<=100&&r.safeguards?.automaticCreditDecisionAllowed===false&&r.safeguards?.humanValidationRequired===true&&Array.isArray(r.documents));}
