import { SECURITY_GOVERNANCE_POLICY } from '../config/securityGovernancePolicies.js';
const ENGINE_VERSION='4.0.0';
const pct=(n,d)=>d?Number((n/d*100).toFixed(1)):0;const avg=a=>a.length?Number((a.reduce((s,x)=>s+x,0)/a.length).toFixed(2)):0;
function metrics(rows){const tp=rows.filter(x=>x.supported&&x.repaid).length,fp=rows.filter(x=>x.supported&&!x.repaid).length,tn=rows.filter(x=>!x.supported&&!x.repaid).length,fn=rows.filter(x=>!x.supported&&x.repaid).length;return{count:rows.length,accuracy:pct(tp+tn,rows.length),precision:pct(tp,tp+fp),recall:pct(tp,tp+fn),supportRate:pct(rows.filter(x=>x.supported).length,rows.length),repaymentRate:pct(rows.filter(x=>x.repaid).length,rows.length),avgScore:avg(rows.map(x=>x.score)),avgConfidence:avg(rows.map(x=>x.confidence))};}
function groupAudit(rows,key,minCell){const groups=[...new Set(rows.map(x=>String(x[key])))];return groups.map(g=>{const r=rows.filter(x=>String(x[key])===g);return{group:g,count:r.length,suppressed:r.length<minCell,...(r.length<minCell?{}:metrics(r))};});}
function maxGap(items,field){const vals=items.filter(x=>!x.suppressed&&Number.isFinite(x[field])).map(x=>x[field]);return vals.length?Number((Math.max(...vals)-Math.min(...vals)).toFixed(1)):0;}
export function validateModelGovernance(dataset,{policy=SECURITY_GOVERNANCE_POLICY}={}){
  const rows=(dataset?.rows||[]).filter(x=>x.synthetic===true);const reference=rows.filter(x=>x.period==='reference'),current=rows.filter(x=>x.period==='current');
  const overall=metrics(rows),referenceMetrics=metrics(reference),currentMetrics=metrics(current);const scoreDrift=Number((currentMetrics.avgScore-referenceMetrics.avgScore).toFixed(2));
  const gender=groupAudit(rows,'gender',policy.minimumFairnessCellSize),age=groupAudit(rows,'ageBand',policy.minimumFairnessCellSize),rural=groupAudit(rows,'rural',policy.minimumFairnessCellSize);
  const fairness={gender,age,rural,maxSupportRateGapPp:Math.max(maxGap(gender,'supportRate'),maxGap(age,'supportRate'),maxGap(rural,'supportRate')),maxRepaymentRateGapPp:Math.max(maxGap(gender,'repaymentRate'),maxGap(age,'repaymentRate'),maxGap(rural,'repaymentRate'))};
  fairness.reviewRequired=fairness.maxSupportRateGapPp>policy.fairnessReviewGapPp||fairness.maxRepaymentRateGapPp>policy.fairnessReviewGapPp;
  const registry={modelId:'INCLUSCORE',modelVersion:'1.2.1',modelType:'deterministic-rule-based-index',intendedUse:'decision-support-only',prohibitedUse:'automatic-credit-approval-or-rejection',validationStatus:'synthetic-only',productionValidated:false,requiredApprovals:policy.requiredModelApprovals,approvedForProduction:false};
  return {engineVersion:ENGINE_VERSION,dataset:{id:dataset.datasetId,synthetic:true,count:rows.length},registry,overall,reference:referenceMetrics,current:currentMetrics,drift:{scorePoints:scoreDrift,reviewRequired:Math.abs(scoreDrift)>=5},fairness,limitations:['synthetic-outcomes-only','not-a-default-probability-validation','not-a-regulatory-fairness-certification','field-pilot-validation-required'],safeguards:{demographicAttributesUsedInIncluscore:false,demographicAttributesUsedForAuditOnly:true,automaticModelPromotionAllowed:false,independentReviewRequired:true}};
}
export function buildModelCard(result){return{schema:'CREDIPASS-MODEL-CARD-1',generatedAt:new Date().toISOString(),registry:result.registry,validation:{dataset:result.dataset,overall:result.overall,drift:result.drift,fairness:result.fairness,limitations:result.limitations},safeguards:result.safeguards};}
export function validateModelValidationResult(r){return Boolean(r?.dataset?.synthetic===true&&r?.registry?.productionValidated===false&&r?.registry?.approvedForProduction===false&&r?.safeguards?.demographicAttributesUsedInIncluscore===false&&r?.safeguards?.automaticModelPromotionAllowed===false);}
