import { REPORTING_ENGINE_VERSION, REPORT_TEMPLATES, listReportTemplates } from '../config/reportingTemplates.js';
const clone=v=>JSON.parse(JSON.stringify(v));
function hash(value){const s=typeof value==='string'?value:JSON.stringify(value);let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(16).toUpperCase().padStart(8,'0');}
function num(v,d=0){const n=Number(v);return Number.isFinite(n)?n.toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';}
function money(v,lang='fr'){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat(lang==='fr'?'fr-FR':'en-US',{maximumFractionDigits:0}).format(n)+' FCFA':'—';}
function pct(v,d=1){const n=Number(v);return Number.isFinite(n)?`${n.toFixed(d)} %`:'—';}
function bool(v,lang){return v?(lang==='fr'?'Oui':'Yes'):(lang==='fr'?'Non':'No');}
function text(v,fallback='—'){return v===undefined||v===null||v===''?fallback:String(v);}
function section(id,title,rows=[],note=null){return{id,title,rows:rows.map(r=>({label:text(r.label),value:text(r.value),note:r.note?text(r.note):null,status:r.status||null})),note};}
function versionRows(ctx){const pairs=[['INCLUSCORE',ctx.incluscore?.engineVersion],['Confiance',ctx.quality?.engineVersion],['Santé financière',ctx.health?.engineVersion],['Dette',ctx.debt?.engineVersion],['Simulation',ctx.simulation?.engineVersion],['Règles',ctx.policyEvaluation?.engineVersion],['Orchestrateur',ctx.recommendation?.engineVersion],['Workflow',ctx.workflow?.engineVersion],['Décision humaine',ctx.humanDecision?.engineVersion],['COOP-SCORE',ctx.coopScore?.engineVersion],['Portefeuille',ctx.portfolioRisk?.engineVersion]];return pairs.filter(x=>x[1]).map(([label,value])=>({label,value:`v${value}`}));}
function baseSubject(ctx){const p=ctx.data?.person||{};return{reference:text(ctx.recommendation?.referenceId||p.id||ctx.portfolioRisk?.portfolioId||'CREDIPASS-SYNTHETIC'),name:text(p.name||ctx.data?.cooperativeProfile?.name||'Portefeuille institutionnel'),city:text(p.city||ctx.data?.cooperativeProfile?.city||'—'),activity:text(p.activityKey||ctx.data?.cooperativeProfile?.activityKey||'—')};}
function translated(lang,fr,en){return lang==='fr'?fr:en;}
function factorRows(items=[],lang='fr'){return items.slice(0,8).map(x=>({label:text(x.label||x.axis||x.id||x.key),value:text(x.value??x.score??x.message??'—'),note:text(x.reason||x.note||'')}));}
function committeeSections(ctx,lang){const decision=ctx.humanDecision;return[
 section('executive',translated(lang,'Synthèse décisionnelle','Decision summary'),[
  {label:translated(lang,'Confiance des données','Data confidence'),value:`${num(ctx.quality?.confidence)} %`},
  {label:'INCLUSCORE',value:`${num(ctx.incluscore?.score)}/100`,note:text(ctx.incluscore?.publishedBand)},
  {label:translated(lang,'Santé financière','Financial health'),value:`${num(ctx.health?.score)}/100`,note:text(ctx.health?.band)},
  {label:translated(lang,'Risque de surendettement','Over-indebtedness risk'),value:`${num(ctx.debt?.overIndebtedness?.score??ctx.debt?.overIndebtedness?.riskScore)}/100`,note:text(ctx.debt?.overIndebtedness?.band)},
  {label:translated(lang,'Montant demandé','Requested amount'),value:money(ctx.simulation?.requestedAmount??ctx.data?.creditRequest?.amount??ctx.data?.profile?.requestedAmount,lang)},
  {label:translated(lang,'Montant proposé','Proposed principal'),value:money(ctx.recommendation?.proposedFinancing?.principal??ctx.simulation?.recommendedPrincipal,lang)},
  {label:translated(lang,'Recommandation moteurs','Engine recommendation'),value:text(ctx.recommendation?.code||ctx.recommendation?.recommendationCode)},
  {label:translated(lang,'Décision humaine','Human decision'),value:decision?text(decision.option||decision.decision):translated(lang,'Non finalisée','Not finalized'),note:decision?.rationale||decision?.reason}
 ]),
 section('controls',translated(lang,'Contrôles et incertitudes','Controls and uncertainties'),[
  {label:translated(lang,'Règles bloquantes','Blocking rules'),value:num(ctx.policyEvaluation?.summary?.failed??ctx.policyEvaluation?.blockingRules?.length??0)},
  {label:translated(lang,'Incertitudes','Uncertainties'),value:num(ctx.recommendation?.uncertainties?.length??ctx.incluscore?.uncertainties?.length??0)},
  {label:translated(lang,'Validation humaine obligatoire','Mandatory human validation'),value:bool(true,lang)},
  {label:translated(lang,'Décision automatique autorisée','Automatic decision allowed'),value:bool(false,lang)}
 ]),
 section('versions',translated(lang,'Versions et traçabilité','Versions and traceability'),versionRows(ctx))
];}
function buildSections(reportId,ctx,lang){
 if(reportId==='committeePack')return committeeSections(ctx,lang);
 if(reportId==='incluscore')return [section('score',translated(lang,'Résultat','Result'),[{label:'INCLUSCORE',value:`${num(ctx.incluscore?.score)}/100`},{label:translated(lang,'Classe publiée','Published band'),value:text(ctx.incluscore?.publishedBand)},{label:translated(lang,'Confiance des données','Data confidence'),value:`${num(ctx.quality?.confidence)} %`}]),section('axes',translated(lang,'Sous-scores','Sub-scores'),(ctx.incluscore?.axes||ctx.incluscore?.axisScores||[]).map(x=>({label:text(x.label||x.id||x.axis),value:`${num(x.score)}/100`,note:x.weight!==undefined?translated(lang,`Pondération ${pct(Number(x.weight)*100)}`,`Weight ${pct(Number(x.weight)*100)}`):null}))),section('factors',translated(lang,'Facteurs et limites','Factors and limits'),factorRows([...(ctx.incluscore?.positiveFactors||[]),...(ctx.incluscore?.negativeFactors||[])],lang)),section('versions',translated(lang,'Versions','Versions'),versionRows(ctx))];
 if(reportId==='dataConfidence')return [section('quality',translated(lang,'Composantes de confiance','Confidence components'),Object.entries(ctx.quality?.components||{}).map(([k,v])=>({label:k,value:`${num(v?.score??v)}/100`,note:v?.weight!==undefined?`weight ${v.weight}`:null}))),section('summary',translated(lang,'Synthèse','Summary'),[{label:translated(lang,'Confiance globale','Overall confidence'),value:`${num(ctx.quality?.confidence)} %`},{label:translated(lang,'Données utilisées','Used data'),value:num(ctx.quality?.used?.length??0)},{label:translated(lang,'Données exclues','Excluded data'),value:num(ctx.quality?.excluded?.length??0)},{label:translated(lang,'Incertitudes','Uncertainties'),value:num(ctx.quality?.uncertainties?.length??0)}]),section('versions',translated(lang,'Versions','Versions'),versionRows(ctx))];
 if(reportId==='financialHealth')return [section('health',translated(lang,'Santé financière','Financial health'),[{label:translated(lang,'Indice','Score'),value:`${num(ctx.health?.score)}/100`},{label:translated(lang,'Classe','Band'),value:text(ctx.health?.band)},{label:translated(lang,'Reste à vivre après dette','Rest-to-live after debt'),value:money(ctx.health?.amounts?.restToLiveAfterDebt,lang)},{label:translated(lang,'Réserve minimale','Minimum reserve'),value:money(ctx.health?.amounts?.minimumRestToLive,lang)},{label:translated(lang,'Nouvelle mensualité prudente','Prudent additional installment'),value:money(ctx.health?.amounts?.safeAdditionalMonthlyPayment,lang)},{label:translated(lang,'Taux de service de la dette','Debt service ratio'),value:pct((ctx.health?.ratios?.debtServiceRatio??0)*100)}]),section('stress',translated(lang,'Résistance aux chocs','Stress resilience'),(ctx.health?.stressTests||[]).map(x=>({label:text(x.id||x.label),value:money(x.restToLiveAfterDebt??x.restToLive,lang),note:text(x.status||x.band||'')}))),section('versions',translated(lang,'Versions','Versions'),versionRows(ctx))];
 if(reportId==='debt')return [section('debt',translated(lang,'Engagements','Commitments'),[{label:translated(lang,'Dettes actives','Active debts'),value:num(ctx.debt?.summary?.activeDebtCount)},{label:translated(lang,'Service mensuel prudent','Prudent monthly debt service'),value:money(ctx.debt?.summary?.conservativeMonthlyService,lang)},{label:translated(lang,'Capital restant dû','Outstanding principal'),value:money(ctx.debt?.summary?.outstandingPrincipal,lang)},{label:translated(lang,'Risque de surendettement','Over-indebtedness risk'),value:`${num(ctx.debt?.overIndebtedness?.score??ctx.debt?.overIndebtedness?.riskScore)}/100`,note:text(ctx.debt?.overIndebtedness?.band)}]),section('flags',translated(lang,'Alertes et rapprochements','Flags and reconciliation'),(ctx.debt?.flags||[]).map(x=>({label:text(x),value:translated(lang,'À examiner','Review')}))),section('versions',translated(lang,'Versions','Versions'),versionRows(ctx))];
 if(reportId==='simulation')return [section('proposal',translated(lang,'Proposition','Proposal'),[{label:translated(lang,'Montant demandé','Requested amount'),value:money(ctx.simulation?.requestedAmount,lang)},{label:translated(lang,'Montant recommandé','Recommended principal'),value:money(ctx.simulation?.recommendedPrincipal??ctx.recommendation?.proposedFinancing?.principal,lang)},{label:translated(lang,'Durée','Duration'),value:`${num(ctx.simulation?.selected?.durationMonths??ctx.simulation?.durationMonths)} ${translated(lang,'mois','months')}`},{label:translated(lang,'Mensualité moyenne','Average installment'),value:money(ctx.simulation?.selected?.averageInstallment??ctx.simulation?.averageInstallment,lang)},{label:translated(lang,'Coût total','Total credit cost'),value:money(ctx.simulation?.selected?.totalCreditCost??ctx.simulation?.totalCreditCost,lang)}]),section('stress',translated(lang,'Stress tests','Stress tests'),(ctx.simulation?.stressTests||[]).map(x=>({label:text(x.id||x.label),value:text(x.status||x.result||'—'),note:x.maximumShortfall!==undefined?money(x.maximumShortfall,lang):null}))),section('versions',translated(lang,'Versions','Versions'),versionRows(ctx))];
 if(reportId==='humanDecision')return [section('recommendation',translated(lang,'Recommandation initiale','Initial recommendation'),[{label:translated(lang,'Code','Code'),value:text(ctx.recommendation?.code||ctx.recommendation?.recommendationCode)},{label:translated(lang,'Montant proposé','Proposed amount'),value:money(ctx.recommendation?.proposedFinancing?.principal,lang)}]),section('decision',translated(lang,'Décision humaine','Human decision'),ctx.humanDecision?[{label:translated(lang,'Décision','Decision'),value:text(ctx.humanDecision.option||ctx.humanDecision.decision)},{label:translated(lang,'Montant','Amount'),value:money(ctx.humanDecision.approvedAmount??ctx.humanDecision.amount,lang)},{label:translated(lang,'Justification','Rationale'),value:text(ctx.humanDecision.rationale||ctx.humanDecision.reason)},{label:translated(lang,'État','Status'),value:text(ctx.humanDecision.status)}]:[{label:translated(lang,'État','Status'),value:translated(lang,'Décision humaine non finalisée','Human decision not finalized')}]),section('appeal',translated(lang,'Recours','Appeal'),[{label:translated(lang,'Recours enregistré','Appeal recorded'),value:bool(Boolean(ctx.appeal),lang)},{label:translated(lang,'État','Status'),value:text(ctx.appeal?.status)}])];
 if(reportId==='progression')return [section('plan',translated(lang,'Plan de progression','Progression plan'),[{label:translated(lang,'Horizon','Horizon'),value:`${num(ctx.progressionPlan?.horizonDays)} ${translated(lang,'jours','days')}`},{label:translated(lang,'Actions','Actions'),value:num(ctx.progressionPlan?.actions?.length)},{label:translated(lang,'Progression suivie','Tracked completion'),value:pct(ctx.progressionTracking?.completionPercent??0)}]),section('actions',translated(lang,'Actions recommandées','Recommended actions'),(ctx.progressionPlan?.actions||[]).slice(0,10).map(x=>({label:text(x.title?.[lang]||x.titleFr||x.titleEn||x.id),value:text(x.status||x.priority),note:text(x.target?.label||x.metric||'')}))),section('projection',translated(lang,'Projection non garantie','Non-guaranteed projection'),[{label:'INCLUSCORE',value:text(ctx.progressionSimulation?.projected?.incluscoreRange||ctx.progressionSimulation?.incluscoreRange)},{label:translated(lang,'Confiance','Confidence'),value:text(ctx.progressionSimulation?.projected?.confidenceRange||ctx.progressionSimulation?.confidenceRange)}])];
 if(reportId==='monitoring')return [section('monitoring',translated(lang,'Suivi','Monitoring'),[{label:translated(lang,'Niveau d’alerte','Alert band'),value:text(ctx.monitoring?.earlyWarning?.band||ctx.monitoring?.summary?.band)},{label:translated(lang,'Indice d’alerte','Alert score'),value:`${num(ctx.monitoring?.earlyWarning?.score??ctx.monitoring?.summary?.riskScore)}/100`},{label:translated(lang,'Observations','Observations'),value:num(ctx.monitoring?.observations?.length)},{label:translated(lang,'Interventions','Interventions'),value:num(ctx.monitoring?.interventions?.length)}]),section('observations',translated(lang,'Dernières observations','Latest observations'),(ctx.monitoring?.observations||[]).slice(-6).map(x=>({label:text(x.period||x.date||x.id),value:money(x.paidAmount??x.installmentPaid??x.actualIncome,lang),note:text(x.status||'')})))];
 if(reportId==='coopScore')return [section('coop',translated(lang,'COOP-SCORE','COOP-SCORE'),ctx.coopScore?[{label:'COOP-SCORE',value:`${num(ctx.coopScore.score)}/100`},{label:translated(lang,'Confiance collective','Collective confidence'),value:`${num(ctx.coopScore.confidence)} %`},{label:translated(lang,'Classe','Band'),value:text(ctx.coopScore.band||ctx.coopScore.publishedBand)}]:[{label:translated(lang,'État','Status'),value:translated(lang,'Non applicable à ce scénario','Not applicable to this scenario')}]),section('axes',translated(lang,'Axes collectifs','Collective axes'),(ctx.coopScore?.axes||[]).map(x=>({label:text(x.label||x.id),value:`${num(x.score)}/100`})))];
 if(reportId==='groupFinancing')return [section('group',translated(lang,'Financement collectif','Group financing'),ctx.groupFinancing?[{label:translated(lang,'Montant','Amount'),value:money(ctx.groupFinancing.principal||ctx.groupFinancing.summary?.principal,lang)},{label:translated(lang,'Couverture des consentements','Consent coverage'),value:pct(ctx.groupFinancing.summary?.consentCoverage??ctx.groupFinancing.consentCoverage)},{label:translated(lang,'Garanties plafonnées','Capped guarantees'),value:money(ctx.groupFinancing.summary?.guaranteeTotal,lang)},{label:translated(lang,'État','Status'),value:text(ctx.groupFinancing.status)}]:[{label:translated(lang,'État','Status'),value:translated(lang,'Non applicable à ce scénario','Not applicable to this scenario')}])];
 if(reportId==='portfolioRisk')return [section('portfolio',translated(lang,'Portefeuille','Portfolio'),[{label:translated(lang,'Dossiers','Accounts'),value:num(ctx.portfolioRisk?.summary?.accountCount??ctx.portfolioRisk?.summary?.dossiers)},{label:translated(lang,'Encours','Outstanding'),value:money(ctx.portfolioRisk?.summary?.totalOutstanding,lang)},{label:'PAR 1',value:pct(ctx.portfolioRisk?.summary?.par1)},{label:'PAR 7',value:pct(ctx.portfolioRisk?.summary?.par7)},{label:'PAR 30',value:pct(ctx.portfolioRisk?.summary?.par30)},{label:translated(lang,'Indice de risque','Portfolio risk score'),value:`${num(ctx.portfolioRisk?.summary?.portfolioRiskScore)}/100`}]),section('watchlist',translated(lang,'Dossiers à revoir','Files to review'),(ctx.portfolioRisk?.watchlist||[]).slice(0,10).map(x=>({label:text(x.name||x.reference||x.id),value:money(x.outstanding,lang),note:text(x.band||x.riskBand||'')})))];
 if(reportId==='institutionalPilot')return [section('readiness',translated(lang,'Préparation institutionnelle','Institutional readiness'),[{label:translated(lang,'Readiness score','Readiness score'),value:`${num(ctx.institutionalPilot?.readiness?.score??ctx.institutionalPilot?.readinessScore)}/100`},{label:translated(lang,'Mode autorisé','Allowed mode'),value:text(ctx.institutionalPilot?.readiness?.allowedMode??ctx.institutionalPilot?.allowedMode)},{label:translated(lang,'Dossiers valides','Valid files'),value:num(ctx.institutionalPilot?.importValidation?.validRows??ctx.institutionalPilot?.comparison?.count)}]),section('roi',translated(lang,'ROI illustratif','Illustrative ROI'),[{label:translated(lang,'Temps manuel moyen','Average manual time'),value:`${num(ctx.institutionalPilot?.comparison?.averageHumanMinutes,1)} min`},{label:translated(lang,'Temps CREDIPASS moyen','Average CREDIPASS time'),value:`${num(ctx.institutionalPilot?.comparison?.averageCredipassMinutes,1)} min`},{label:translated(lang,'Convergence','Convergence'),value:pct(ctx.institutionalPilot?.comparison?.convergenceRate??0)}])];
 if(reportId==='verification')return [section('verification',translated(lang,'Priorité de vérification','Verification priority'),[{label:translated(lang,'Indice','Score'),value:`${num(ctx.trustVerification?.score)}/100`},{label:translated(lang,'Niveau','Band'),value:text(ctx.trustVerification?.band)},{label:translated(lang,'Signaux','Findings'),value:num(ctx.trustVerification?.findings?.length)},{label:translated(lang,'Fraude automatique','Automatic fraud conclusion'),value:bool(false,lang)}]),section('findings',translated(lang,'Signaux à examiner','Signals to review'),(ctx.trustVerification?.findings||[]).slice(0,10).map(x=>({label:text(x.type||x.id),value:text(x.severity||x.band),note:text(x.description||x.reason||'')})))];
 if(reportId==='fieldOperations')return [section('field',translated(lang,'Terrain et synchronisation','Field and synchronization'),[{label:translated(lang,'Missions','Missions'),value:num(ctx.fieldWorkspace?.missions?.length)},{label:translated(lang,'Opérations en file','Queued operations'),value:num(ctx.fieldWorkspace?.summary?.queued)},{label:translated(lang,'Opérations synchronisées','Synced operations'),value:num(ctx.fieldWorkspace?.summary?.synced)},{label:translated(lang,'Conflits','Conflicts'),value:num(ctx.fieldWorkspace?.summary?.conflicts)},{label:translated(lang,'Réseau','Network'),value:text(ctx.fieldWorkspace?.networkMode)}]),section('missions',translated(lang,'Missions','Missions'),(ctx.fieldWorkspace?.missions||[]).map(x=>({label:text(x.title||x.id),value:text(x.status),note:text(x.assignedAgent?.name||'')})))];
 return [section('unknown',translated(lang,'Rapport indisponible','Report unavailable'),[{label:'ID',value:reportId}])];
}
export function buildProfessionalReport(ctx={},options={}){
 const lang=options.lang==='en'?'en':'fr';const reportId=options.reportId||'committeePack';const template=REPORT_TEMPLATES[reportId]||REPORT_TEMPLATES.committeePack;const generatedAt=options.generatedAt||'2026-08-07T09:30:00.000Z';const subject=baseSubject(ctx);const sections=buildSections(template.id,ctx,lang);const decisionFinal=Boolean(ctx.humanDecision&&['final','communicated'].includes(ctx.humanDecision.status));const ref=`RPT-${hash([REPORTING_ENGINE_VERSION,template.id,lang,subject.reference,ctx.recommendation?.referenceId,ctx.quality?.confidence,ctx.incluscore?.score,ctx.health?.score,ctx.humanDecision?.status||'none'])}`;
 return{engineVersion:REPORTING_ENGINE_VERSION,templateVersion:`2.9.0-${template.id}`,reportId:template.id,reportReference:ref,language:lang,title:template.title[lang],description:template.description[lang],audience:template.audience,category:template.category,generatedAt,subject,sections,decisionStatus:decisionFinal?'final-human-decision-recorded':'human-decision-not-finalized',disclaimer:translated(lang,'Document d’aide à l’analyse. Aucun score ou rapport CREDIPASS ne constitue à lui seul une décision de crédit. Les données du environnement local sont synthétiques.','Decision-support document. No CREDIPASS score or report constitutes a credit decision by itself. Synthetic data are synthetic.'),safeguards:{automaticCreditDecisionAllowed:false,rawSensitiveDocumentsEmbedded:false,humanValidationRequired:true,syntheticDemoDataDeclared:true,reportDoesNotAlterSourceData:true},sourceVersions:versionRows(ctx)};
}
export function buildReportingWorkspace(ctx={},options={}){const lang=options.lang==='en'?'en':'fr';const selectedReportId=REPORT_TEMPLATES[options.selectedReportId]?options.selectedReportId:'committeePack';const report=buildProfessionalReport(ctx,{lang,reportId:selectedReportId,generatedAt:options.generatedAt});return{engineVersion:REPORTING_ENGINE_VERSION,workspaceId:`REPORTING-${hash([selectedReportId,lang,report.reportReference])}`,selectedReportId,templates:listReportTemplates().map(t=>({id:t.id,title:t.title[lang],description:t.description[lang],audience:t.audience,category:t.category})),report,summary:{templateCount:listReportTemplates().length,sectionCount:report.sections.length,rowCount:report.sections.reduce((a,s)=>a+s.rows.length,0),humanDecisionFinal:report.decisionStatus==='final-human-decision-recorded'},safeguards:clone(report.safeguards)};}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
export function reportToHtml(report){const rows=report.sections.map(s=>`<section><h2>${escapeHtml(s.title)}</h2>${s.note?`<p class="note">${escapeHtml(s.note)}</p>`:''}<table><tbody>${s.rows.map(r=>`<tr><th>${escapeHtml(r.label)}</th><td>${escapeHtml(r.value)}</td><td>${escapeHtml(r.note||'')}</td></tr>`).join('')}</tbody></table></section>`).join('');return`<!doctype html><html lang="${report.language}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(report.title)} — ${escapeHtml(report.reportReference)}</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#17231d;margin:0;line-height:1.35}.brand{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #0f5132;padding-bottom:12px;margin-bottom:18px}.brand h1{margin:0;color:#0f5132;font-size:24px}.brand strong{color:#a5761b}.meta{font-size:12px;color:#59665f;text-align:right}h2{font-size:15px;color:#0f5132;margin:18px 0 8px}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #dbe3df;padding:7px;vertical-align:top}th{width:34%;text-align:left;background:#f4f8f6}.notice{margin-top:18px;padding:10px;background:#fff8e7;border-left:4px solid #a5761b;font-size:11px}.footer{margin-top:18px;border-top:1px solid #dbe3df;padding-top:8px;font-size:10px;color:#65716b}.signature{margin-top:28px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.signature div{border-top:1px solid #aab5af;padding-top:6px;font-size:11px}@media print{.no-print{display:none}}</style></head><body><div class="brand"><div><strong>KABU PRO</strong><h1>CREDIPASS</h1><p>${escapeHtml(report.title)}</p></div><div class="meta">${escapeHtml(report.reportReference)}<br>${escapeHtml(report.generatedAt)}</div></div><p><strong>${report.language==='fr'?'Sujet':'Subject'} :</strong> ${escapeHtml(report.subject.name)} · ${escapeHtml(report.subject.reference)} · ${escapeHtml(report.subject.city)}</p>${rows}<div class="notice">${escapeHtml(report.disclaimer)}</div><div class="signature"><div>${report.language==='fr'?'Analyste / Agent':'Analyst / Officer'}</div><div>${report.language==='fr'?'Validation humaine finale':'Final human validation'}</div></div><div class="footer">CREDIPASS by KABU PRO · ${escapeHtml(report.reportReference)} · ${report.language.toUpperCase()} · ${report.safeguards.automaticCreditDecisionAllowed?'AUTO':'HUMAN-CONTROLLED'}</div></body></html>`;}
function csvEscape(v){const s=String(v??'');return /[",\n;]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
export function reportToCsv(report){const rows=[[report.language==='fr'?'Section':'Section',report.language==='fr'?'Indicateur':'Indicator',report.language==='fr'?'Valeur':'Value',report.language==='fr'?'Note':'Note']];for(const s of report.sections)for(const r of s.rows)rows.push([s.title,r.label,r.value,r.note||'']);return '\ufeff'+rows.map(row=>row.map(csvEscape).join(';')).join('\r\n');}
export function validateProfessionalReport(r){return Boolean(r?.engineVersion===REPORTING_ENGINE_VERSION&&r?.reportReference&&r?.title&&['fr','en'].includes(r.language)&&Array.isArray(r.sections)&&r.sections.length>0&&r.sections.every(s=>s.id&&s.title&&Array.isArray(s.rows))&&r.safeguards?.automaticCreditDecisionAllowed===false&&r.safeguards?.humanValidationRequired===true&&r.safeguards?.reportDoesNotAlterSourceData===true);}
export function validateReportingWorkspace(w){return Boolean(w?.engineVersion===REPORTING_ENGINE_VERSION&&w?.workspaceId&&Array.isArray(w.templates)&&w.templates.length>=15&&validateProfessionalReport(w.report)&&w.safeguards?.automaticCreditDecisionAllowed===false);}
