const CACHE='credipass.auth.lastUser', OFFLINE='credipass.auth.offline.v1', ATTEMPTS='credipass.auth.offline.attempts';
const enc=new TextEncoder();
function b64(bytes){return btoa(String.fromCharCode(...bytes))}
function unb64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function derive(password,salt,iterations=180000){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations,hash:'SHA-256'},key,256);return b64(new Uint8Array(bits))}
function readOffline(){try{return JSON.parse(localStorage.getItem(OFFLINE)||'{}')}catch{return{}}}
function readAttempts(){try{return JSON.parse(localStorage.getItem(ATTEMPTS)||'{}')}catch{return{}}}
export async function enrollOfflineCredential(user,password){if(!user?.login||!password)return;const all=readOffline(),salt=crypto.getRandomValues(new Uint8Array(16));all[user.login]={user,salt:b64(salt),iterations:180000,verifier:await derive(password,salt),enrolledAt:new Date().toISOString()};localStorage.setItem(OFFLINE,JSON.stringify(all));localStorage.setItem(CACHE,JSON.stringify(user));}
export async function verifyOfflineLogin(login,password){const attempts=readAttempts(),a=attempts[login]||{count:0,lockedUntil:0};if(a.lockedUntil>Date.now())throw Error('Accès hors connexion temporairement verrouillé après plusieurs tentatives.');const rec=readOffline()[login];if(!rec)throw Error('Première authentification en ligne requise sur cet appareil.');const got=await derive(password,unb64(rec.salt),rec.iterations);if(got!==rec.verifier){a.count=(a.count||0)+1;if(a.count>=5){a.lockedUntil=Date.now()+5*60_000;a.count=0}attempts[login]=a;localStorage.setItem(ATTEMPTS,JSON.stringify(attempts));throw Error('Identifiant ou mot de passe incorrect.');}delete attempts[login];localStorage.setItem(ATTEMPTS,JSON.stringify(attempts));return rec.user}
export async function apiLogin(login,password){const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({login,password})});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'Authentification refusée');const {user}=await r.json();await enrollOfflineCredential(user,password);return user}

export async function apiChangePassword(currentPassword,newPassword){const r=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({currentPassword,newPassword})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Modification du mot de passe refusée');return j.user||null}
export async function apiLogout(){try{await fetch('/api/auth/logout',{method:'POST',credentials:'include'})}catch{}localStorage.removeItem(CACHE)}
export async function apiMe(){try{const r=await fetch('/api/auth/me',{credentials:'include'});if(!r.ok)return null;const {user}=await r.json();localStorage.setItem(CACHE,JSON.stringify(user));return user}catch{return null}}
export function cachedOfflineUser(login){try{const all=readOffline();return all[login]?.user||null}catch{return null}}

export async function apiUpdateProfile(profile){let r;try{r=await fetch('/api/auth/profile',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(profile)})}catch{throw Error('Connexion au serveur requise pour modifier le profil.')}const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Modification du profil refusée');return j.user||null}
