const clean=s=>String(s??'').trim();
const num=v=>Number.isFinite(Number(v))?Number(v):0;
export const WIZARD_STEPS=['Client','Demande','Activité & flux','Dettes & garanties','Documents & preuves','Vérification'];
export function createDraft(seed={}){return {id:seed.id||`BR-${Date.now()}`,step:Math.max(0,Math.min(5,num(seed.step))),client:{id:clean(seed.client?.id),name:clean(seed.client?.name),type:clean(seed.client?.type)||'Personne physique',city:clean(seed.client?.city),phone:clean(seed.client?.phone)},request:{reference:clean(seed.request?.reference),amount:num(seed.request?.amount),durationMonths:num(seed.request?.durationMonths)||12,purpose:clean(seed.request?.purpose)},activity:{label:clean(seed.activity?.label),monthlyIncome:num(seed.activity?.monthlyIncome),monthlyExpenses:num(seed.activity?.monthlyExpenses),seasonal:Boolean(seed.activity?.seasonal)},debts:{monthlyPayment:num(seed.debts?.monthlyPayment),guarantees:clean(seed.debts?.guarantees),collateral:clean(seed.debts?.collateral)},documents:Array.isArray(seed.documents)?seed.documents:[],updatedAt:new Date().toISOString()};}
export function validateDraft(d){const e=[];if(!clean(d?.client?.name))e.push('Nom / raison sociale manquant');if(!clean(d?.client?.city))e.push('Ville manquante');if(!clean(d?.request?.reference))e.push('Référence dossier manquante');if(num(d?.request?.amount)<=0)e.push('Montant demandé invalide');if(num(d?.request?.durationMonths)<=0)e.push('Durée invalide');return {valid:!e.length,errors:e,completeness:Math.round((5-e.length)/5*100)};}
export function documentStatus(doc,now=new Date()){if(doc.rejected)return 'Rejeté';if(doc.expiresAt&&new Date(doc.expiresAt)<now)return 'Expiré';if(doc.verified)return 'Vérifié';return doc.received===false?'À recevoir':'À vérifier';}
export function contradictionReview({declaredIncome=0,reconstructedIncome=0,declaredExpenses=0,reconstructedExpenses=0}={}){const out=[];const add=(label,a,b)=>{const base=Math.max(Math.abs(num(a)),1),gap=Math.abs(num(a)-num(b))/base;if(gap>=.2)out.push({label,declared:num(a),reconstructed:num(b),gapPercent:Math.round(gap*100),severity:gap>=.4?'Élevée':'À vérifier'});};add('Revenus',declaredIncome,reconstructedIncome);add('Dépenses',declaredExpenses,reconstructedExpenses);return out;}
export function nextBestAction({draft,contradictions=[],documents=[]}={}){const v=validateDraft(draft||{});if(!v.valid)return `Compléter : ${v.errors[0]}`;const pending=documents.find(x=>documentStatus(x)!=='Vérifié');if(pending)return `Vérifier le document : ${pending.name||'pièce reçue'}`;if(contradictions.length)return `Examiner l’incohérence : ${contradictions[0].label}`;return 'Poursuivre l’analyse du dossier';}
export function parseCsv(text){const lines=String(text||'').replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return [];const sep=lines[0].includes(';')?';':',';const h=lines[0].split(sep).map(clean);return lines.slice(1).map(line=>Object.fromEntries(line.split(sep).map((v,i)=>[h[i],clean(v)])));}
export const IMPORT_TEMPLATE='reference;clientName;clientType;city;phone;requestedAmount;durationMonths;purpose;monthlyIncome;monthlyExpenses;monthlyDebt\nDOS-2026-007;Client Exemple;Personne physique;Bamako;;300000;12;Fonds de roulement;250000;140000;0\n';
export function previewImport(rows){return rows.map((r,i)=>{const normalized={reference:clean(r.reference),name:clean(r.clientName||r.name),applicantType:clean(r.clientType||r.applicantType)||'Personne physique',city:clean(r.city),phone:clean(r.phone),requestedAmount:num(r.requestedAmount),durationMonths:num(r.durationMonths),purpose:clean(r.purpose),informalIncome:num(r.monthlyIncome||r.informalIncome),essentialExpenses:num(r.monthlyExpenses||r.essentialExpenses),debtPayment:num(r.monthlyDebt||r.debtPayment)};const errors=[];if(!normalized.reference)errors.push('Référence manquante');if(!normalized.name)errors.push('Client manquant');if(!normalized.city)errors.push('Ville manquante');if(normalized.requestedAmount<=0)errors.push('Montant invalide');if(normalized.durationMonths<=0)errors.push('Durée invalide');return {row:i+1,normalized,valid:!errors.length,errors};});}
