import * as B from './creditLedgerV2.js';
export const TYPES=B.TYPES; export const addMember=B.addMember; export const updateMember=B.updateMember; export const addApplication=B.addApplication; export const updateApplication=B.updateApplication; export const addDocument=B.addDocument; export const addVisit=B.addVisit; export const addFinancial=B.addFinancial; export const addGuarantee=B.addGuarantee; export const recordDecision=B.recordDecision; export const disburse=B.disburse; export const pay=B.pay; export const restructure=B.restructure; export const close=B.close; export const financialPosition=B.financialPosition; export const position=B.position;
const KEY='credipass.credit-ledger.r13'; const iso=()=>new Date().toISOString();
function init(x){for(const k of ['trustObservations','schedules','followups','alerts','recommendations'])x[k]??=[];x.version=13;return x}
export function seed(){const x=init(B.seed()); const cases=[
['MEM-0001',900000,12,520000,250000,80000,20000,'Commerce de céréales'],
['MEM-0002',1500000,18,850000,410000,120000,35000,'Équipement de transformation'],
['MEM-0003',5000000,24,4200000,2600000,500000,180000,'Extension distribution'],
['MEM-0004',3000000,18,2600000,1450000,300000,120000,'Campagne maraîchère']];
for(const [memberId,amt,dur,rev,biz,hh,debt,purpose] of cases){const a=B.addApplication(x,{memberId,product:'Crédit activité',purpose,requestedAmount:amt,durationMonths:dur,periodicity:'Mensuelle'},'Démonstration');B.addDocument(x,{applicationId:a.id,label:'Pièce d’identité / document légal',status:'Vérifié',source:'Documenté',reference:'DEMO'},'Démonstration');B.addDocument(x,{applicationId:a.id,label:'Justificatif activité',status:'Vérifié',source:'Documenté',reference:'DEMO'},'Démonstration');B.addVisit(x,{applicationId:a.id,addressVerified:'Oui',activityObserved:'Oui',stock:'Observé',equipment:'Observé',observations:'Activité constatée et cohérente avec les informations fournies.'},'Agent terrain');B.addFinancial(x,{applicationId:a.id,revenue:rev,businessExpenses:biz,householdExpenses:hh,debtPayments:debt,source:'Déclaré + documenté'},'Analyste');B.addGuarantee(x,{applicationId:a.id,type:'Matériel',description:'Équipement professionnel',owner:'Membre',declaredValue:amt*.8,expertValue:amt*.65,retainedValue:amt*.55,status:'Expertisée'},'Expert');addTrust(x,{applicationId:a.id,dimension:'Vérification terrain',fact:'Activité effectivement constatée lors de la visite.',source:'Observé',effect:'Favorable',verified:'Oui'},'Agent terrain');addTrust(x,{applicationId:a.id,dimension:'Cohérence déclarative',fact:'Les flux déclarés sont cohérents avec les pièces disponibles.',source:'Documenté',effect:'Favorable',verified:'Oui'},'Analyste');addTrust(x,{applicationId:a.id,dimension:'Transparence / coopération',fact:'Les informations demandées ont été fournies et vérifiables.',source:'Documenté',effect:'Favorable',verified:'Oui'},'Agent');}
return x}
export function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)return init(x)}catch{}return seed()}
export function save(x){localStorage.setItem(KEY,JSON.stringify(init(x)));return x}
function log(x,action,actor='Utilisateur',detail={}){x.audit.unshift({at:iso(),action,actor,...detail});x.audit=x.audit.slice(0,1500)}
const next=(p,a)=>`${p}-${String(a.length+1).padStart(4,'0')}`;
export function addTrust(x,d,actor){const v={id:next('TRU',x.trustObservations),applicationId:d.applicationId,dimension:d.dimension||'Cohérence déclarative',fact:d.fact||'',source:d.source||'Observé',effect:d.effect||'Neutre',verified:d.verified||'Oui',at:iso(),actor};if(!v.fact)throw Error('Fait observable obligatoire');x.trustObservations.push(v);log(x,'CARACTÈRE_DOCUMENTÉ',actor,{applicationId:d.applicationId});return v}
export function trustSummary(x,id){const a=x.trustObservations.filter(v=>v.applicationId===id),verified=a.filter(v=>v.verified==='Oui').length,pos=a.filter(v=>v.effect==='Favorable').length,warn=a.filter(v=>v.effect==='Vigilance').length;return {count:a.length,verified,pos,warn,level:a.length>=4&&verified/a.length>=.75?'Élevé':a.length>=2?'Moyen':'Faible',items:a}}
export function confidence(x,id){const docs=x.documents.filter(v=>v.applicationId===id),vis=x.visits.filter(v=>v.applicationId===id),fin=x.financials.filter(v=>v.applicationId===id),gar=x.guarantees.filter(v=>v.applicationId===id),tru=x.trustObservations.filter(v=>v.applicationId===id);let score=0;score+=Math.min(25,docs.filter(v=>v.status==='Vérifié').length*8);score+=vis.length?20:0;score+=fin.length?20:0;score+=Math.min(20,gar.filter(v=>v.status==='Vérifiée'||v.status==='Expertisée').length*10);score+=Math.min(15,tru.filter(v=>v.verified==='Oui').length*5);return Math.min(100,score)}
export function risk(x,id){const f=B.financialPosition(x,id),a=x.applications.find(v=>v.id===id);if(!a)return 0;const capRatio=a.requestedAmount?Math.min(1,f.capacity/(a.requestedAmount/Math.max(1,a.durationMonths))):0;const conf=confidence(x,id)/100;const t=trustSummary(x,id);const trust=Math.max(0,Math.min(1,.55+(t.pos-t.warn)*.08));return Math.round(1000*(.45*capRatio+.30*conf+.25*trust))}
export function simulate(x,id,amount,duration,rate=18){const f=B.financialPosition(x,id);amount=+amount||0;duration=+duration||12;const interest=amount*(+rate||0)/100;const total=amount+interest;const installment=total/duration;return {amount,duration,rate,interest,total,installment,capacity:f.capacity,margin:f.capacity-installment,sustainable:f.capacity>=installment}}
export function recommend(x,id){const a=x.applications.find(v=>v.id===id),f=B.financialPosition(x,id);if(!a)return null;const max=Math.max(0,Math.floor((f.capacity*a.durationMonths/1.18)/10000)*10000);const amount=Math.min(a.requestedAmount,max);const sim=simulate(x,id,amount,a.durationMonths,18);return {amount,duration:a.durationMonths,periodicity:a.periodicity,reason:sim.sustainable?'Compatible avec la capacité calculée':'Réduction nécessaire pour préserver la marge',simulation:sim}}
export function generateSchedule(x,id,rate=18,startDate){const a=x.applications.find(v=>v.id===id),p=B.position(x,id);if(!a||p.disbursed<=0)throw Error('Décaissement requis');x.schedules=x.schedules.filter(v=>v.applicationId!==id);const n=Math.max(1,a.durationMonths),principal=p.disbursed/n,interest=p.disbursed*(+rate||0)/100/n;let d=new Date(startDate||Date.now());for(let i=1;i<=n;i++){d=new Date(d);d.setMonth(d.getMonth()+1);x.schedules.push({id:`ECH-${id}-${i}`,applicationId:id,no:i,dueDate:d.toISOString().slice(0,10),principal,interest,amount:principal+interest})}log(x,'ÉCHÉANCIER_GÉNÉRÉ','Système',{applicationId:id});return schedule(x,id)}
export function schedule(x,id){return x.schedules.filter(v=>v.applicationId===id).map(v=>{const paid=x.payments.filter(p=>p.applicationId===id).reduce((s,p)=>s+p.amount,0);const previous=x.schedules.filter(z=>z.applicationId===id&&z.no<v.no).reduce((s,z)=>s+z.amount,0);const allocated=Math.max(0,Math.min(v.amount,paid-previous));const due=new Date(v.dueDate)<new Date()&&allocated+1<v.amount;return {...v,paid:allocated,balance:Math.max(0,v.amount-allocated),late:due}})}
export function addFollowup(x,d,actor){const v={id:next('SUI',x.followups),applicationId:d.applicationId,type:d.type||'Appel',note:d.note||'',nextAction:d.nextAction||'',nextDate:d.nextDate||'',at:iso(),actor};x.followups.push(v);log(x,'SUIVI_ENREGISTRÉ',actor,{applicationId:d.applicationId});return v}
export function alerts(x){const out=[];for(const a of x.applications){const late=schedule(x,a.id).filter(v=>v.late);if(late.length)out.push({applicationId:a.id,type:'RETARD',severity:'Élevée',message:`${late.length} échéance(s) en retard`});if(confidence(x,a.id)<50&&!['CLÔTURÉ','REFUSÉ'].includes(a.status))out.push({applicationId:a.id,type:'DONNÉES',severity:'Moyenne',message:'Confiance des données à renforcer'})}return out}
export function par(x){const active=x.applications.filter(a=>B.position(x,a.id).outstanding>0),risky=active.filter(a=>schedule(x,a.id).some(v=>v.late));const enc=active.reduce((s,a)=>s+B.position(x,a.id).outstanding,0),risk=risky.reduce((s,a)=>s+B.position(x,a.id).outstanding,0);return {active:active.length,risky:risky.length,encours:enc,riskEncours:risk,rate:enc?risk/enc*100:0}}
export function metrics(x){const b=B.metrics(x),p=par(x);return {...b,par:p.rate,riskEncours:p.riskEncours,alerts:alerts(x).length}}
export function dossier(x,id){const d=B.dossier(x,id);return {...d,trust:trustSummary(x,id),confidence:confidence(x,id),incluscore:risk(x,id),recommendation:recommend(x,id),schedule:schedule(x,id),followups:x.followups.filter(v=>v.applicationId===id),alerts:alerts(x).filter(v=>v.applicationId===id)}}
export function passport(x,memberId){return x.applications.filter(a=>a.memberId===memberId).map(a=>({application:a,position:B.position(x,a.id),decision:[...x.decisions].reverse().find(v=>v.applicationId===a.id),payments:x.payments.filter(v=>v.applicationId===a.id),restructures:x.restructures.filter(v=>v.applicationId===a.id)}))}
