const KEY='credipass.credit-ledger.v2';
const iso=()=>new Date().toISOString();
const next=(prefix,arr)=>`${prefix}-${String(arr.length+1).padStart(4,'0')}`;
export const TYPES=['Personne physique','Entrepreneur individuel','Personne morale','Groupe / Coopérative'];
export function seed(){return {version:2,members:[
{id:'MEM-0001',memberNo:'M-1001',type:TYPES[0],name:'Aïssata Traoré',phone:'76 00 10 01',city:'Bamako',activity:'Commerce de céréales',joinedAt:'2024-02-10'},
{id:'MEM-0002',memberNo:'M-1002',type:TYPES[1],name:'Fatoumata Diallo',phone:'76 00 10 02',city:'Sikasso',activity:'Transformation agroalimentaire',joinedAt:'2023-07-18'},
{id:'MEM-0003',memberNo:'M-1003',type:TYPES[2],name:'Kanu Agro SARL',phone:'76 00 10 03',city:'Koutiala',activity:'Agro-distribution',joinedAt:'2022-11-03'},
{id:'MEM-0004',memberNo:'M-1004',type:TYPES[3],name:'Coopérative Benkadi',phone:'76 00 10 04',city:'Ségou',activity:'Production maraîchère',joinedAt:'2021-05-21'}],applications:[],documents:[],visits:[],financials:[],guarantees:[],decisions:[],disbursements:[],payments:[],restructures:[],audit:[{at:iso(),action:'REGISTRE_INITIALISÉ',actor:'Système'}]}}
export function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?.version===2?x:seed()}catch{return seed()}}
export function save(x){localStorage.setItem(KEY,JSON.stringify(x));return x}
function log(x,action,actor='Utilisateur',detail={}){x.audit.unshift({at:iso(),action,actor,...detail});x.audit=x.audit.slice(0,1000)}
export function addMember(x,d,actor){const m={id:next('MEM',x.members),memberNo:d.memberNo||`M-${1001+x.members.length}`,type:d.type||TYPES[0],name:d.name?.trim(),phone:d.phone||'',city:d.city||'',activity:d.activity||'',joinedAt:d.joinedAt||iso().slice(0,10)};if(!m.name)throw Error('Nom du membre obligatoire');x.members.push(m);log(x,'MEMBRE_CRÉÉ',actor,{memberId:m.id});return m}
export function updateMember(x,id,d,actor){const m=x.members.find(v=>v.id===id);if(!m)throw Error('Membre introuvable');Object.assign(m,{memberNo:d.memberNo||m.memberNo,type:d.type||m.type,name:d.name||m.name,phone:d.phone??m.phone,city:d.city??m.city,activity:d.activity??m.activity});log(x,'MEMBRE_MODIFIÉ',actor,{memberId:id});return m}
export function addApplication(x,d,actor){if(!x.members.some(m=>m.id===d.memberId))throw Error('Membre obligatoire');const a={id:next('DOS',x.applications),memberId:d.memberId,product:d.product||'Crédit activité',purpose:d.purpose||'',requestedAmount:+d.requestedAmount||0,durationMonths:+d.durationMonths||12,periodicity:d.periodicity||'Mensuelle',status:'BROUILLON',createdAt:iso()};x.applications.push(a);log(x,'DEMANDE_CRÉÉE',actor,{applicationId:a.id});return a}
export function updateApplication(x,id,d,actor){const a=x.applications.find(v=>v.id===id);if(!a)throw Error('Dossier introuvable');for(const k of ['product','purpose','periodicity'])if(d[k]!=null)a[k]=d[k];for(const k of ['requestedAmount','durationMonths'])if(d[k]!=null)a[k]=+d[k]||0;log(x,'DEMANDE_MODIFIÉE',actor,{applicationId:id});return a}
export function addDocument(x,d,actor){const v={id:next('DOC',x.documents),applicationId:d.applicationId,label:d.label||'Document',status:d.status||'Reçu',source:d.source||'Documenté',reference:d.reference||'',at:iso()};x.documents.push(v);touch(x,d.applicationId,'À COMPLÉTER');log(x,'DOCUMENT_AJOUTÉ',actor,{applicationId:d.applicationId,documentId:v.id});return v}
export function addVisit(x,d,actor){const v={id:next('VIS',x.visits),applicationId:d.applicationId,addressVerified:d.addressVerified||'Oui',activityObserved:d.activityObserved||'Oui',stock:d.stock||'',equipment:d.equipment||'',observations:d.observations||'',at:iso(),actor};x.visits.push(v);touch(x,d.applicationId,'EN VÉRIFICATION');log(x,'VISITE_TERRAIN',actor,{applicationId:d.applicationId,visitId:v.id});return v}
export function addFinancial(x,d,actor){const f={id:next('FIN',x.financials),applicationId:d.applicationId,revenue:+d.revenue||0,businessExpenses:+d.businessExpenses||0,householdExpenses:+d.householdExpenses||0,debtPayments:+d.debtPayments||0,source:d.source||'Déclaré',at:iso()};x.financials.push(f);touch(x,d.applicationId,'EN ANALYSE');log(x,'ANALYSE_FINANCIÈRE',actor,{applicationId:d.applicationId,financialId:f.id});return f}
export function addGuarantee(x,d,actor){const g={id:next('GAR',x.guarantees),applicationId:d.applicationId,type:d.type||'Matériel',description:d.description||'',owner:d.owner||'',declaredValue:+d.declaredValue||0,expertValue:d.expertValue===''||d.expertValue==null?null:+d.expertValue,retainedValue:d.retainedValue===''||d.retainedValue==null?null:+d.retainedValue,status:d.status||'À vérifier',at:iso()};x.guarantees.push(g);log(x,'GARANTIE_AJOUTÉE',actor,{applicationId:d.applicationId,guaranteeId:g.id});return g}
export function recordDecision(x,d,actor){const a=app(x,d.applicationId);const v={id:next('DEC',x.decisions),applicationId:d.applicationId,decision:d.decision,approvedAmount:d.decision==='VALIDÉ'?+d.approvedAmount||0:0,reason:d.reason||'',conditions:d.conditions||'',actor,at:iso()};x.decisions.push(v);a.status=d.decision;log(x,'DÉCISION_ENREGISTRÉE',actor,{applicationId:a.id,decision:v.decision});return v}
export function disburse(x,d,actor){const a=app(x,d.applicationId);const last=[...x.decisions].reverse().find(v=>v.applicationId===a.id&&v.decision==='VALIDÉ');if(!last)throw Error('Décision VALIDÉE requise avant décaissement');const already=sum(x.disbursements.filter(v=>v.applicationId===a.id),'amount');const amount=+d.amount||0;if(amount<=0||already+amount>last.approvedAmount)throw Error('Montant de décaissement invalide');const v={id:next('DECAIS',x.disbursements),applicationId:a.id,amount,method:d.method||'Caisse',reference:d.reference||'',at:iso(),actor};x.disbursements.push(v);a.status='DÉCAISSÉ';log(x,'DÉCAISSEMENT',actor,{applicationId:a.id,amount});return v}
export function pay(x,d,actor){const a=app(x,d.applicationId);const amount=+d.amount||0,interest=+d.interest||0;if(amount<=0||interest<0||interest>amount)throw Error('Paiement invalide');const outstanding=position(x,a.id).outstanding;const principal=Math.min(outstanding,amount-interest);const v={id:next('PAY',x.payments),applicationId:a.id,amount,principal,interest,method:d.method||'Caisse',reference:d.reference||'',at:iso(),actor};x.payments.push(v);if(position(x,a.id).outstanding<=0)a.status='CLÔTURÉ';log(x,'REMBOURSEMENT',actor,{applicationId:a.id,amount});return v}
export function restructure(x,d,actor){const a=app(x,d.applicationId);const v={id:next('RST',x.restructures),applicationId:a.id,reason:d.reason||'',evidence:d.evidence||'',newDuration:+d.newDuration||a.durationMonths,newPeriodicity:d.newPeriodicity||a.periodicity,at:iso(),actor};x.restructures.push(v);a.durationMonths=v.newDuration;a.periodicity=v.newPeriodicity;a.status='EN SUIVI';log(x,'RESTRUCTURATION',actor,{applicationId:a.id});return v}
export function close(x,id,actor){const a=app(x,id);if(position(x,id).outstanding>0)throw Error('Clôture impossible : encours restant');a.status='CLÔTURÉ';log(x,'CRÉDIT_CLÔTURÉ',actor,{applicationId:id});return a}
function touch(x,id,status){const a=x.applications.find(v=>v.id===id);if(a&&!['VALIDÉ','REFUSÉ','DÉCAISSÉ','CLÔTURÉ'].includes(a.status))a.status=status}
function app(x,id){const a=x.applications.find(v=>v.id===id);if(!a)throw Error('Dossier introuvable');return a}
const sum=(a,k)=>a.reduce((s,v)=>s+(+v[k]||0),0);
export function financialPosition(x,id){const f=[...x.financials].reverse().find(v=>v.applicationId===id);if(!f)return {revenue:0,expenses:0,capacity:0,source:'Non renseigné'};const expenses=f.businessExpenses+f.householdExpenses+f.debtPayments;return {...f,expenses,capacity:Math.max(0,f.revenue-expenses)}}
export function position(x,id){const disbursed=sum(x.disbursements.filter(v=>v.applicationId===id),'amount'),principalPaid=sum(x.payments.filter(v=>v.applicationId===id),'principal');return {disbursed,principalPaid,outstanding:Math.max(0,disbursed-principalPaid)}}
export function metrics(x){const requested=sum(x.applications,'requestedAmount'),approved=sum(x.decisions.filter(v=>v.decision==='VALIDÉ'),'approvedAmount'),disbursed=sum(x.disbursements,'amount'),principalPaid=sum(x.payments,'principal'),outstanding=Math.max(0,disbursed-principalPaid);return {members:x.members.length,applications:x.applications.length,requested,approved,disbursed,outstanding,inProgress:x.applications.filter(a=>!['REFUSÉ','CLÔTURÉ'].includes(a.status)).length}}
export function dossier(x,id){const a=app(x,id);return {application:a,member:x.members.find(m=>m.id===a.memberId),documents:x.documents.filter(v=>v.applicationId===id),visits:x.visits.filter(v=>v.applicationId===id),financials:x.financials.filter(v=>v.applicationId===id),guarantees:x.guarantees.filter(v=>v.applicationId===id),decisions:x.decisions.filter(v=>v.applicationId===id),disbursements:x.disbursements.filter(v=>v.applicationId===id),payments:x.payments.filter(v=>v.applicationId===id),restructures:x.restructures.filter(v=>v.applicationId===id),financial:financialPosition(x,id),position:position(x,id)}}
