import * as B from './creditLedgerV2.js';
const KEY='credipass.credit-ledger.r14', iso=()=>new Date().toISOString(), num=v=>Number(v)||0;
const sum=(a,k)=>a.reduce((s,v)=>s+num(v[k]),0), next=(p,a)=>`${p}-${String(a.length+1).padStart(4,'0')}`;
export const TYPES=B.TYPES;
const ARR=['checklists','incomeItems','expenseItems','debts','trustObservations','schedules','scheduleVersions','followups','alertsLog','recommendations','memberUsers'];
function init(x){ARR.forEach(k=>x[k]??=[]);x.version=14;return x}
function log(x,action,actor='Utilisateur',detail={}){x.audit.unshift({at:iso(),action,actor,...detail});x.audit=x.audit.slice(0,2500)}
export function seed(){const x=init(B.seed()); const cases=[['MEM-0001',900000,12,520000,250000,80000,20000,'Commerce de céréales'],['MEM-0002',1500000,18,850000,410000,120000,35000,'Équipement de transformation'],['MEM-0003',5000000,24,4200000,2600000,500000,180000,'Extension distribution'],['MEM-0004',3000000,18,2600000,1450000,300000,120000,'Campagne maraîchère']];
for(const [memberId,amt,dur,rev,biz,hh,debt,purpose] of cases){const a=B.addApplication(x,{memberId,product:'Crédit activité',purpose,requestedAmount:amt,durationMonths:dur,periodicity:'Mensuelle'},'Démonstration');ensureChecklist(x,a.id);['Identité / document légal','Justificatif activité','Demande signée'].forEach((label,i)=>{B.addDocument(x,{applicationId:a.id,label,status:'Vérifié',source:'Documenté',reference:`DEMO-${i+1}`},'Démonstration');completeChecklist(x,a.id,label)});B.addVisit(x,{applicationId:a.id,addressVerified:'Oui',activityObserved:'Oui',stock:'Observé',equipment:'Observé',observations:'Activité constatée et cohérente.',customerFlow:'Régulier',activityAge:'24',geoReference:'Terrain'},'Agent terrain');addIncome(x,{applicationId:a.id,label:'Ventes / revenus',amount:rev,frequency:'Mensuelle',source:'Documenté'},'Analyste');addExpense(x,{applicationId:a.id,label:'Charges activité',amount:biz,category:'Activité'},'Analyste');addExpense(x,{applicationId:a.id,label:'Charges ménage',amount:hh,category:'Ménage'},'Analyste');addDebt(x,{applicationId:a.id,creditor:'Engagement existant',outstanding:debt*8,installment:debt,status:'Actif',source:'Déclaré + vérifié'},'Analyste');B.addGuarantee(x,{applicationId:a.id,type:'Matériel',description:'Équipement professionnel',owner:'Membre',declaredValue:amt*.8,expertValue:amt*.65,retainedValue:amt*.55,status:'Expertisée'},'Expert');addTrust(x,{applicationId:a.id,dimension:'Vérification terrain',fact:'Activité effectivement constatée.',source:'Observé',effect:'Favorable',verified:'Oui'},'Agent terrain');addTrust(x,{applicationId:a.id,dimension:'Cohérence déclarative',fact:'Flux cohérents avec les pièces.',source:'Documenté',effect:'Favorable',verified:'Oui'},'Analyste');addTrust(x,{applicationId:a.id,dimension:'Transparence / coopération',fact:'Informations demandées fournies.',source:'Documenté',effect:'Favorable',verified:'Oui'},'Agent');x.memberUsers.push({id:`USR-${memberId}`,memberId,login:x.members.find(m=>m.id===memberId)?.memberNo,pin:'1234',enabled:true});}return x}
export function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?init(x):seed()}catch{return seed()}} export function save(x){localStorage.setItem(KEY,JSON.stringify(init(x)));return x}
export const addMember=(x,d,a)=>B.addMember(x,d,a); export const updateMember=(x,id,d,a)=>B.updateMember(x,id,d,a);
export function addApplication(x,d,actor){const a=B.addApplication(x,d,actor);ensureChecklist(x,a.id);return a} export const updateApplication=(x,id,d,a)=>B.updateApplication(x,id,d,a);
const REQUIRED=['Identité / document légal','Justificatif activité','Demande signée','Preuve adresse / localisation','Justificatifs de revenus / activité'];
export function ensureChecklist(x,id){if(!x.checklists.some(c=>c.applicationId===id))REQUIRED.forEach(label=>x.checklists.push({id:next('CHK',x.checklists),applicationId:id,label,required:true,status:'Manquant'}));return checklist(x,id)}
export function checklist(x,id){const items=x.checklists.filter(c=>c.applicationId===id),done=items.filter(c=>c.status==='Vérifié').length;return {items,required:items.length,done,percent:items.length?Math.round(done/items.length*100):0,complete:items.length>0&&done===items.length}}
function completeChecklist(x,id,label){const c=x.checklists.find(v=>v.applicationId===id&&(v.label===label||label.toLowerCase().includes(v.label.toLowerCase().split(' / ')[0])));if(c)c.status='Vérifié'}
export function addDocument(x,d,actor){const v=B.addDocument(x,d,actor);if(v.status==='Vérifié')completeChecklist(x,d.applicationId,v.label);log(x,'CHECKLIST_MISE_À_JOUR',actor,{applicationId:d.applicationId});return v}
export function addVisit(x,d,actor){const v=B.addVisit(x,d,actor);Object.assign(v,{customerFlow:d.customerFlow||'',activityAge:num(d.activityAge),geoReference:d.geoReference||'',references:d.references||'',verificationResult:d.verificationResult||'Cohérent'});return v}
export function addIncome(x,d,actor){const v={id:next('REV',x.incomeItems),applicationId:d.applicationId,label:d.label||'Revenu',amount:num(d.amount),frequency:d.frequency||'Mensuelle',source:d.source||'Déclaré',verified:d.verified||'Oui',at:iso()};x.incomeItems.push(v);log(x,'REVENU_AJOUTÉ',actor,{applicationId:d.applicationId,id:v.id});return v}
export function addExpense(x,d,actor){const v={id:next('CHG',x.expenseItems),applicationId:d.applicationId,label:d.label||'Charge',amount:num(d.amount),category:d.category||'Activité',source:d.source||'Déclaré',at:iso()};x.expenseItems.push(v);log(x,'CHARGE_AJOUTÉE',actor,{applicationId:d.applicationId,id:v.id});return v}
export function addDebt(x,d,actor){const v={id:next('DET',x.debts),applicationId:d.applicationId,creditor:d.creditor||'',initialAmount:num(d.initialAmount),outstanding:num(d.outstanding),installment:num(d.installment),status:d.status||'Actif',source:d.source||'Déclaré',bicStatus:d.bicStatus||'Non renseigné',at:iso()};x.debts.push(v);log(x,'DETTE_AJOUTÉE',actor,{applicationId:d.applicationId,id:v.id});return v}
export function financialPosition(x,id){const inc=sum(x.incomeItems.filter(v=>v.applicationId===id),'amount'),biz=sum(x.expenseItems.filter(v=>v.applicationId===id&&v.category==='Activité'),'amount'),hh=sum(x.expenseItems.filter(v=>v.applicationId===id&&v.category==='Ménage'),'amount'),other=sum(x.expenseItems.filter(v=>v.applicationId===id&&!['Activité','Ménage'].includes(v.category)),'amount'),debt=sum(x.debts.filter(v=>v.applicationId===id&&v.status==='Actif'),'installment'),expenses=biz+hh+other+debt,capacity=Math.max(0,inc-expenses);return {revenue:inc,businessExpenses:biz,householdExpenses:hh,otherExpenses:other,debtPayments:debt,expenses,capacity,marginRatio:inc?capacity/inc*100:0,source:'Éléments structurés'}}
export function addTrust(x,d,actor){if(!d.fact?.trim())throw Error('Fait observable obligatoire');const v={id:next('TRU',x.trustObservations),applicationId:d.applicationId,dimension:d.dimension||'Cohérence déclarative',fact:d.fact.trim(),source:d.source||'Observé',effect:d.effect||'Neutre',verified:d.verified||'Oui',at:iso(),actor};x.trustObservations.push(v);log(x,'CARACTÈRE_DOCUMENTÉ',actor,{applicationId:d.applicationId,id:v.id});return v}
export function trustSummary(x,id){const a=x.trustObservations.filter(v=>v.applicationId===id),verified=a.filter(v=>v.verified==='Oui').length,pos=a.filter(v=>v.effect==='Favorable').length,warn=a.filter(v=>v.effect==='Vigilance').length;return {count:a.length,verified,pos,warn,level:a.length>=4&&verified/a.length>=.75?'Élevé':a.length>=2?'Moyen':'Faible',items:a}}
export function confidence(x,id){const c=checklist(x,id),vis=x.visits.filter(v=>v.applicationId===id),gar=x.guarantees.filter(v=>v.applicationId===id),t=trustSummary(x,id),fin=financialPosition(x,id);let s=c.percent*.30+(vis.length?15:0)+(fin.revenue>0?20:0)+Math.min(15,gar.filter(g=>['Vérifiée','Expertisée'].includes(g.status)).length*10)+Math.min(20,t.verified*5);return Math.round(Math.min(100,s))}
export function incluscore(x,id){const f=financialPosition(x,id),a=x.applications.find(v=>v.id===id);if(!a)return null;const t=trustSummary(x,id),conf=confidence(x,id),gar=sum(x.guarantees.filter(g=>g.applicationId===id),'retainedValue'),debts=sum(x.debts.filter(d=>d.applicationId===id&&d.status==='Actif'),'outstanding');const monthlyNeed=a.requestedAmount/Math.max(1,a.durationMonths),axes={capacity:Math.min(100,f.capacity/Math.max(1,monthlyNeed)*70),margin:Math.min(100,f.marginRatio*4),debt:Math.max(0,100-(f.revenue?f.debtPayments/f.revenue*200:100)),evidence:conf,character:Math.max(0,Math.min(100,60+(t.pos-t.warn)*10)),collateral:Math.min(100,gar/Math.max(1,a.requestedAmount)*100),continuity:Math.min(100,(x.visits.filter(v=>v.applicationId===id).at(-1)?.activityAge||0)/36*100)};const weights={capacity:.25,margin:.15,debt:.15,evidence:.15,character:.10,collateral:.10,continuity:.10};const score100=Object.entries(weights).reduce((s,[k,w])=>s+axes[k]*w,0);return {score:Math.round(score100*10),axes,weights,confidence:conf,debts,explanation:Object.entries(axes).map(([k,v])=>({axis:k,score:Math.round(v),weight:weights[k]}))}}
export function productPolicy(a){return {annualRate:18,interestMethod:'Dégressif',feesRate:3,insuranceRate:0,gracePeriods:0,periodicity:a.periodicity||'Mensuelle'}}
function periodsPerYear(p){return p==='Hebdomadaire'?52:p==='Trimestrielle'?4:p==='Saisonnière'?2:12} function totalPeriods(months,p){return Math.max(1,Math.round(months*periodsPerYear(p)/12))}
export function simulate(x,id,amount,duration,periodicity,rate,method='Dégressif'){const a=x.applications.find(v=>v.id===id),f=financialPosition(x,id);amount=num(amount);duration=num(duration)||a?.durationMonths||12;periodicity=periodicity||a?.periodicity||'Mensuelle';rate=num(rate)||18;const n=totalPeriods(duration,periodicity),r=rate/100/periodsPerYear(periodicity);let balance=amount,totalInterest=0,maxPayment=0;if(method==='Plat'){totalInterest=amount*rate/100*duration/12;maxPayment=(amount+totalInterest)/n}else{const principal=amount/n;for(let i=0;i<n;i++){const interest=balance*r;totalInterest+=interest;maxPayment=Math.max(maxPayment,principal+interest);balance-=principal}}const monthlyEquivalent=maxPayment*periodsPerYear(periodicity)/12;return {amount,duration,periodicity,rate,method,periods:n,totalInterest,total:amount+totalInterest,installment:maxPayment,monthlyEquivalent,capacity:f.capacity,margin:f.capacity-monthlyEquivalent,sustainable:f.capacity>=monthlyEquivalent}}
export function recommend(x,id){const a=x.applications.find(v=>v.id===id),f=financialPosition(x,id);if(!a)return null;const p=productPolicy(a);let lo=0,hi=a.requestedAmount;for(let i=0;i<24;i++){const mid=(lo+hi)/2;if(simulate(x,id,mid,a.durationMonths,a.periodicity,p.annualRate,p.interestMethod).sustainable)lo=mid;else hi=mid}const amount=Math.floor(lo/10000)*10000,simulation=simulate(x,id,amount,a.durationMonths,a.periodicity,p.annualRate,p.interestMethod);return {amount,duration:a.durationMonths,periodicity:a.periodicity,policy:p,reason:amount>=a.requestedAmount?'Demande compatible avec la capacité calculée':'Montant prudent réduit pour préserver la capacité de remboursement',simulation}}
export function recordDecision(x,d,actor){const c=checklist(x,d.applicationId);if(d.decision==='VALIDÉ'&&!c.complete)throw Error('Constitution incomplète : pièces obligatoires non vérifiées');const v=B.recordDecision(x,d,actor);Object.assign(v,{authority:d.authority||'Comité de crédit',meetingRef:d.meetingRef||'',conditions:d.conditions||''});return v}
export const addGuarantee=(x,d,a)=>B.addGuarantee(x,d,a); export const disburse=(x,d,a)=>B.disburse(x,d,a);
export function generateSchedule(x,id,opts={}){const a=x.applications.find(v=>v.id===id),p=B.position(x,id);if(!a||p.disbursed<=0)throw Error('Décaissement requis');const policy={...productPolicy(a),...opts},n=totalPeriods(a.durationMonths,a.periodicity),ppy=periodsPerYear(a.periodicity),r=policy.annualRate/100/ppy,principal=p.outstanding/n,version=(x.scheduleVersions.filter(v=>v.applicationId===id).at(-1)?.version||0)+1,start=new Date(opts.startDate||Date.now());x.schedules.filter(v=>v.applicationId===id&&v.active).forEach(v=>v.active=false);let balance=p.outstanding;for(let i=1;i<=n;i++){const d=new Date(start);if(a.periodicity==='Hebdomadaire')d.setDate(d.getDate()+7*i);else if(a.periodicity==='Trimestrielle')d.setMonth(d.getMonth()+3*i);else if(a.periodicity==='Saisonnière')d.setMonth(d.getMonth()+6*i);else d.setMonth(d.getMonth()+i);const interest=policy.interestMethod==='Plat'?p.outstanding*policy.annualRate/100*a.durationMonths/12/n:balance*r;const pr=i===n?balance:principal;x.schedules.push({id:`ECH-${id}-V${version}-${i}`,applicationId:id,version,no:i,dueDate:d.toISOString().slice(0,10),principal:pr,interest,amount:pr+interest,active:true});balance-=pr}x.scheduleVersions.push({applicationId:id,version,createdAt:iso(),reason:opts.reason||'Échéancier initial',policy});log(x,'ÉCHÉANCIER_GÉNÉRÉ','Système',{applicationId:id,version});return schedule(x,id)}
export function schedule(x,id){const rows=x.schedules.filter(v=>v.applicationId===id&&v.active),payments=x.payments.filter(v=>v.applicationId===id),paid=sum(payments,'amount');let consumed=0;return rows.map(v=>{const alloc=Math.max(0,Math.min(v.amount,paid-consumed));consumed+=v.amount;const days=Math.max(0,Math.floor((Date.now()-new Date(v.dueDate))/86400000)),late=days>0&&alloc+1<v.amount;return {...v,paid:alloc,balance:Math.max(0,v.amount-alloc),late,daysPastDue:late?days:0}})}
export function pay(x,d,actor){const due=schedule(x,d.applicationId),amount=num(d.amount);if(amount<=0)throw Error('Paiement invalide');let remaining=amount,interest=0,principal=0;for(const e of due){if(remaining<=0)break;const iDue=Math.max(0,e.interest-Math.min(e.interest,e.paid)),i=Math.min(remaining,iDue);interest+=i;remaining-=i;const pDue=Math.max(0,e.principal-Math.max(0,e.paid-e.interest)),pr=Math.min(remaining,pDue);principal+=pr;remaining-=pr}if(remaining>0)principal+=remaining;return B.pay(x,{...d,amount,interest:Math.min(interest,amount)},actor)}
export function restructure(x,d,actor){const a=x.applications.find(v=>v.id===d.applicationId),before={duration:a.durationMonths,periodicity:a.periodicity,scheduleVersion:x.scheduleVersions.filter(v=>v.applicationId===a.id).at(-1)?.version||0};const v=B.restructure(x,d,actor);generateSchedule(x,a.id,{reason:`Restructuration: ${d.reason||''}`,annualRate:num(d.annualRate)||18,interestMethod:d.interestMethod||'Dégressif'});v.before=before;v.after={duration:a.durationMonths,periodicity:a.periodicity,scheduleVersion:x.scheduleVersions.filter(z=>z.applicationId===a.id).at(-1)?.version};return v}
export function addFollowup(x,d,actor){const v={id:next('SUI',x.followups),applicationId:d.applicationId,type:d.type||'Appel',note:d.note||'',nextAction:d.nextAction||'',nextDate:d.nextDate||'',result:d.result||'',at:iso(),actor};x.followups.push(v);log(x,'SUIVI_ENREGISTRÉ',actor,{applicationId:d.applicationId,id:v.id});return v}
export function alerts(x){const out=[];for(const a of x.applications){const late=schedule(x,a.id).filter(v=>v.late);if(late.length)out.push({applicationId:a.id,type:'RETARD',severity:Math.max(...late.map(v=>v.daysPastDue))>=30?'Critique':'Élevée',daysPastDue:Math.max(...late.map(v=>v.daysPastDue)),message:`${late.length} échéance(s) en retard`});if(confidence(x,a.id)<60&&!['CLÔTURÉ','REFUSÉ'].includes(a.status))out.push({applicationId:a.id,type:'DONNÉES',severity:'Moyenne',message:'Confiance des données à renforcer'})}return out}
export function par(x,days=1){const active=x.applications.filter(a=>B.position(x,a.id).outstanding>0),risk=active.filter(a=>schedule(x,a.id).some(v=>v.daysPastDue>=days)),enc=active.reduce((s,a)=>s+B.position(x,a.id).outstanding,0),riskEncours=risk.reduce((s,a)=>s+B.position(x,a.id).outstanding,0);return {days,active:active.length,risky:risk.length,encours:enc,riskEncours,rate:enc?riskEncours/enc*100:0}}
export function metrics(x){const b=B.metrics(x),p1=par(x,1),p7=par(x,7),p30=par(x,30);return {...b,par:p1.rate,par1:p1.rate,par7:p7.rate,par30:p30.rate,riskEncours:p1.riskEncours,alerts:alerts(x).length}}
export function close(x,id,actor){return B.close(x,id,actor)} export const position=(x,id)=>B.position(x,id);
export function dossier(x,id){const base=B.dossier(x,id),inc=incluscore(x,id);return {...base,financial:financialPosition(x,id),checklist:checklist(x,id),incomeItems:x.incomeItems.filter(v=>v.applicationId===id),expenseItems:x.expenseItems.filter(v=>v.applicationId===id),debts:x.debts.filter(v=>v.applicationId===id),trust:trustSummary(x,id),confidence:confidence(x,id),incluscore:inc?.score||0,incluscoreDetail:inc,recommendation:recommend(x,id),schedule:schedule(x,id),scheduleVersions:x.scheduleVersions.filter(v=>v.applicationId===id),followups:x.followups.filter(v=>v.applicationId===id),alerts:alerts(x).filter(v=>v.applicationId===id)} }
export function passport(x,memberId){return x.applications.filter(a=>a.memberId===memberId).map(a=>({application:a,position:B.position(x,a.id),decision:[...x.decisions].reverse().find(v=>v.applicationId===a.id),payments:x.payments.filter(v=>v.applicationId===a.id),restructures:x.restructures.filter(v=>v.applicationId===a.id),followups:x.followups.filter(v=>v.applicationId===a.id),scheduleVersions:x.scheduleVersions.filter(v=>v.applicationId===a.id)}))}
export function memberLogin(x,login,pin){const u=x.memberUsers.find(v=>v.enabled&&v.login===login&&v.pin===pin);return u?x.members.find(m=>m.id===u.memberId):null}
export function reportData(x){return {generatedAt:iso(),metrics:metrics(x),members:x.members.length,decisions:{validated:x.decisions.filter(v=>v.decision==='VALIDÉ').length,adjourned:x.decisions.filter(v=>v.decision==='AJOURNÉ').length,refused:x.decisions.filter(v=>v.decision==='REFUSÉ').length},portfolio:[1,7,30].map(d=>par(x,d)),auditCount:x.audit.length}}
// Compatibilité UI R13 : convertit l'ancien formulaire agrégé en écritures structurées.
export function addFinancial(x,d,actor){x.incomeItems=x.incomeItems.filter(v=>v.applicationId!==d.applicationId);x.expenseItems=x.expenseItems.filter(v=>v.applicationId!==d.applicationId);x.debts=x.debts.filter(v=>v.applicationId!==d.applicationId);addIncome(x,{applicationId:d.applicationId,label:'Revenus / CA',amount:d.revenue,source:d.source||'Déclaré'},actor);addExpense(x,{applicationId:d.applicationId,label:'Charges activité',amount:d.businessExpenses,category:'Activité',source:d.source},actor);addExpense(x,{applicationId:d.applicationId,label:'Charges ménage',amount:d.householdExpenses,category:'Ménage',source:d.source},actor);if(num(d.debtPayments)>0)addDebt(x,{applicationId:d.applicationId,creditor:'Engagements existants',installment:d.debtPayments,outstanding:num(d.debtPayments)*6,source:d.source},actor);log(x,'ANALYSE_FINANCIÈRE_STRUCTURÉE',actor,{applicationId:d.applicationId});return financialPosition(x,d.applicationId)}
