const iso=()=>new Date().toISOString();
const next=(p,a)=>`${p}-${String((a?.length||0)+1).padStart(4,'0')}`;
export function ensureR187(db){db.bicChecks??=[];db.dataDisputes??=[];db.importJobs??=[];db.dataCorrections??=[];return db}
export function recordBic(db,input,actor='Utilisateur'){ensureR187(db);if(!input.applicationId)throw Error('Dossier obligatoire');const v={id:next('BIC',db.bicChecks),applicationId:input.applicationId,consultedAt:input.consultedAt||iso().slice(0,10),source:input.source||'BIC — saisie manuelle',reference:input.reference||'',commitments:Number(input.commitments)||0,incidents:input.incidents||'Aucun incident renseigné',observation:input.observation||'',evidence:input.evidence||'',actor,at:iso()};db.bicChecks.push(v);db.audit.unshift({at:v.at,action:'BIC_ENREGISTRÉ',actor,applicationId:v.applicationId,bicId:v.id});return v}
export function bicFor(db,applicationId){ensureR187(db);return db.bicChecks.filter(x=>x.applicationId===applicationId)}
export function disputeData(db,input,actor='Utilisateur'){ensureR187(db);if(!input.applicationId||!input.field)throw Error('Dossier et donnée contestée obligatoires');const v={id:next('CON',db.dataDisputes),applicationId:input.applicationId,field:input.field,currentValue:input.currentValue??'',requestedValue:input.requestedValue??'',reason:input.reason||'',evidence:input.evidence||'',status:'OUVERTE',openedBy:actor,openedAt:iso()};db.dataDisputes.push(v);db.audit.unshift({at:v.openedAt,action:'CONTESTATION_OUVERTE',actor,applicationId:v.applicationId,disputeId:v.id,field:v.field});return v}
export function resolveDispute(db,id,{decision,newValue,note}={},actor='Utilisateur'){ensureR187(db);const v=db.dataDisputes.find(x=>x.id===id);if(!v)throw Error('Contestation introuvable');if(!['ACCEPTÉE','REJETÉE'].includes(decision))throw Error('Décision invalide');v.status=decision;v.resolvedAt=iso();v.resolvedBy=actor;v.note=note||'';if(decision==='ACCEPTÉE'){db.dataCorrections.push({id:next('COR',db.dataCorrections),applicationId:v.applicationId,field:v.field,oldValue:v.currentValue,newValue:newValue??v.requestedValue,reason:v.reason,evidence:v.evidence,actor,at:v.resolvedAt});v.appliedValue=newValue??v.requestedValue}db.audit.unshift({at:v.resolvedAt,action:'CONTESTATION_'+decision,actor,applicationId:v.applicationId,disputeId:v.id});return v}
export function auditFor(db,applicationId){return (db.audit||[]).filter(x=>x.applicationId===applicationId).sort((a,b)=>String(b.at).localeCompare(String(a.at)))}
export function registerImport(db,{fileName,memberRows=0,applicationRows=0,errors=[]},actor='Administrateur Système'){ensureR187(db);const v={id:next('IMP',db.importJobs),fileName,memberRows,applicationRows,status:errors.length?'AVEC_ANOMALIES':'VALIDÉ',errors:[...errors],actor,at:iso()};db.importJobs.unshift(v);db.audit.unshift({at:v.at,action:'IMPORT_DONNÉES',actor,importId:v.id,fileName,memberRows,applicationRows,errors:errors.length});return v}
export function passportSummary(db,memberId){ensureR187(db);const apps=(db.applications||[]).filter(a=>a.memberId===memberId),ids=new Set(apps.map(a=>a.id));return {applications:apps.length,decisions:(db.decisions||[]).filter(x=>ids.has(x.applicationId)).length,payments:(db.payments||[]).filter(x=>ids.has(x.applicationId)).length,restructures:(db.restructures||[]).filter(x=>ids.has(x.applicationId)).length,bic:db.bicChecks.filter(x=>ids.has(x.applicationId)).length,disputes:db.dataDisputes.filter(x=>ids.has(x.applicationId)).length,audit:(db.audit||[]).filter(x=>ids.has(x.applicationId)).length}}
