import {createSyncEnvelope,structureIdForAgency,zoneIdForAgency,DEFAULT_INSTITUTION} from './decentralizedR191.js';
const KEY='credipass.r18.syncQueue',FORCE='credipass.field.offline',NODE='credipass.node.id',CENTRAL_VERSION='credipass.central.version';
export const SYNC_APP_COLLECTIONS=['documents','visits','financials','guarantees','decisions','disbursements','payments','restructures','checklists','incomeItems','expenseItems','debts','trustObservations','schedules','scheduleVersions','followups','alertsLog','recommendations','productForms','policyChecks','institutionalRisk','businessAnalyses','personalBudgets','personalBalanceSheets','workflowActions','consents','bicChecks','dataDisputes','dataCorrections','audit'];
const parse=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
function uid(){const c=globalThis.crypto;return c?.randomUUID?.()||`${Date.now()}-${Math.floor(Math.random()*1e9)}`}
export function currentNodeId(user={}){let id=localStorage.getItem(NODE);if(id)return id;const sid=user.structureId||structureIdForAgency(user.agency);id=`NODE-${String(sid).replace(/^STR-/,'')}-${uid().slice(0,8).toUpperCase()}`;localStorage.setItem(NODE,id);return id}
export function enqueue(type,entityId,detail={},context={}){const q=parse(),entity=context.entity||{id:entityId,type,agency:context.user?.agency,structureId:context.user?.structureId,zoneId:context.user?.zoneIds?.[0],institutionId:context.user?.institutionId,syncVersion:context.baseVersion||0};const nodeId=context.nodeId||currentNodeId(context.user||{}),envelope=createSyncEnvelope(entity,context.actor||context.user?.login||'SYSTEM',nodeId);const op={id:envelope.eventId,type,entityId,detail,nodeId:envelope.nodeId,institutionId:envelope.institutionId||DEFAULT_INSTITUTION.id,structureId:envelope.structureId||structureIdForAgency(context.user?.agency),zoneId:envelope.zoneId||zoneIdForAgency(context.user?.agency),baseVersion:envelope.baseVersion,targetVersion:envelope.targetVersion,envelope,createdAt:envelope.at,status:'EN_ATTENTE'};q.push(op);localStorage.setItem(KEY,JSON.stringify(q));return op}
export function queue(){return parse()}
export function pendingCount(){return parse().filter(x=>x.status==='EN_ATTENTE'||x.status==='CONFLIT').length}
export function conflictCount(){return parse().filter(x=>x.status==='CONFLIT').length}
export function forcedOffline(){return localStorage.getItem(FORCE)==='1'}
export function setForcedOffline(v){localStorage.setItem(FORCE,v?'1':'0');globalThis.window?.dispatchEvent?.(new Event('credipass-connectivity'));return forcedOffline()}
export function connectionState(){return forcedOffline()||globalThis.navigator?.onLine===false?'HORS_CONNEXION':'EN_LIGNE'}
export function lastSync(){return localStorage.getItem('credipass.r18.lastSync')||'Jamais'}
export function markLocalSave(){localStorage.setItem('credipass.r18.lastLocalSave',new Date().toISOString())}
export function lastLocalSave(){return localStorage.getItem('credipass.r18.lastLocalSave')||null}
function appIdOf(x){return String(x?.applicationId||x?.appId||'')}
export function mergeCentralSnapshot(local,remote,{preserveEntityIds=[]}={}){if(!remote)return local;const preserve=new Set((preserveEntityIds||[]).map(String)),remoteApps=new Set((remote.applications||[]).map(x=>String(x.id)));
  const mergeTop=(k,keyFn)=>{const map=new Map((local[k]||[]).map(x=>[String(keyFn(x)),x]).filter(([id])=>id));for(const x of remote[k]||[]){const id=String(keyFn(x)||'');if(id&&!preserve.has(id))map.set(id,x)}local[k]=[...map.values()]};
  mergeTop('members',x=>x?.id);mergeTop('applications',x=>x?.id);
  for(const k of SYNC_APP_COLLECTIONS){const keep=(local[k]||[]).filter(x=>{const aid=appIdOf(x);return !remoteApps.has(aid)||preserve.has(aid)}),fresh=(remote[k]||[]).filter(x=>!preserve.has(appIdOf(x)));local[k]=[...keep,...fresh]}
  for(const k of ['creditProducts','productPolicyVersions','sfdFieldProfiles','importJobs'])if(Array.isArray(remote[k]))local[k]=structuredClone(remote[k]);
  if(remote.activeSfdFieldProfileId)local.activeSfdFieldProfileId=remote.activeSfdFieldProfileId;if(Number.isFinite(Number(remote.syncConfigVersion)))local.syncConfigVersion=Number(remote.syncConfigVersion);if(remote.organisation)local.organisation=structuredClone(remote.organisation);return local}
export async function syncNow(snapshot,context={}){if(connectionState()==='HORS_CONNEXION')return{ok:false,offline:true,message:'Mode hors connexion actif.'};const all=parse(),operations=all.filter(x=>x.status==='EN_ATTENTE'),existingConflicts=all.filter(x=>x.status==='CONFLIT'),baseCentralVersion=Number(localStorage.getItem(CENTRAL_VERSION)||0);try{const r=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({operations,snapshot,baseCentralVersion,node:{id:context.nodeId||currentNodeId(context.user||{}),institutionId:context.user?.institutionId,structureId:context.user?.structureId,zoneIds:context.user?.zoneIds||[]}})});const pushed=await r.json().catch(()=>({}));if(!r.ok)throw Error(pushed.error||`HTTP ${r.status}`);const accepted=new Set(pushed.acceptedIds||[]),conflictMap=new Map((pushed.conflicts||[]).map(c=>[c.eventId,c]));const next=parse().filter(x=>!accepted.has(x.id)).map(x=>conflictMap.has(x.id)?{...x,status:'CONFLIT',conflict:conflictMap.get(x.id)}:x);localStorage.setItem(KEY,JSON.stringify(next));const pull=await fetch('/api/sync/pull',{credentials:'include'});if(!pull.ok)throw Error(`Pull HTTP ${pull.status}`);const central=await pull.json();localStorage.setItem(CENTRAL_VERSION,String(central.version||pushed.version||0));localStorage.setItem('credipass.r18.lastSync',new Date().toISOString());const preserveEntityIds=[...new Set([...existingConflicts.map(x=>x.entityId),...(pushed.conflicts||[]).map(x=>x.entityId)])];return{ok:true,...pushed,remoteSnapshot:central.snapshot,version:central.version,preserveEntityIds}}
catch(e){return{ok:false,message:`Synchronisation différée : ${e.message}`}}}
export async function resolveQueuedConflict(eventId,resolution){const q=parse(),op=q.find(x=>x.id===eventId&&x.status==='CONFLIT');if(!op)throw Error('Conflit local introuvable');const r=await fetch('/api/sync/resolve',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({eventId,resolution})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||`HTTP ${r.status}`);let next;if(resolution==='KEEP_CENTRAL')next=q.filter(x=>x.id!==eventId);else next=q.map(x=>x.id===eventId?{...x,status:'EN_ATTENTE',baseVersion:j.nextBaseVersion,targetVersion:j.nextTargetVersion,envelope:{...(x.envelope||{}),baseVersion:j.nextBaseVersion,targetVersion:j.nextTargetVersion},conflict:null}:x);localStorage.setItem(KEY,JSON.stringify(next));return{...j,operation:next.find(x=>x.id===eventId)||null}}
export function syncCapability(){return{centralBackend:true,message:connectionState()==='HORS_CONNEXION'?'Travail local actif. Les opérations seront synchronisées au retour en ligne.':'Synchronisation institutionnelle centrale disponible.'}}
