const clone=x=>JSON.parse(JSON.stringify(x));
export const PRODUCT_STATUS=['BROUILLON','VALIDÉ','ACTIF','RETIRÉ'];
export const DEFAULT_PRODUCTS=[
 {code:'SALARIE',name:'Crédit salarié',family:'Salarié',profiles:['Personne physique'],minAmount:100000,maxAmount:5000000,minMonths:3,maxMonths:36,periodicities:['Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité','Demande signée','Justificatif de salaire','Justificatif employeur / contrat'],guarantees:['Selon politique institutionnelle'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'SAL-1.0',status:'ACTIF',source:'Référentiel CREDIPASS — paramètres configurables'},
 {code:'PME',name:'Crédit PME',family:'Commerce / PME',profiles:['Entrepreneur individuel','Personne morale'],minAmount:100000,maxAmount:25000000,minMonths:3,maxMonths:36,periodicities:['Mensuelle','Trimestrielle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité','Demande signée','Justificatif activité / entreprise','Documents légaux applicables','Justificatifs de revenus / activité','Justificatifs de garanties'],guarantees:['Épargne/caution/matériel/autre selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'PME-1.0',status:'ACTIF',source:'Référentiel CREDIPASS — paramètres configurables'},
 {code:'COMMERCE',name:'Crédit commerce',family:'Commerce',profiles:['Entrepreneur individuel','Personne morale'],minAmount:50000,maxAmount:15000000,minMonths:3,maxMonths:24,periodicities:['Hebdomadaire','Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité','Preuve activité','Preuves de flux'],guarantees:['Selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'COM-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'AGRICOLE',name:'Crédit agricole / campagne',family:'Agriculture',profiles:['Entrepreneur individuel','Groupe / Coopérative','Personne morale'],minAmount:100000,maxAmount:25000000,minMonths:3,maxMonths:24,periodicities:['Saisonnière','Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:3,requiredDocs:['Pièce d’identité / document légal','Preuve activité agricole','Plan/campagne ou estimation de production'],guarantees:['Selon filière et politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'AGR-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'ELEVAGE',name:'Crédit élevage',family:'Élevage',profiles:['Entrepreneur individuel','Groupe / Coopérative'],minAmount:100000,maxAmount:15000000,minMonths:3,maxMonths:24,periodicities:['Saisonnière','Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:2,requiredDocs:['Pièce d’identité','Preuve activité élevage','Visite terrain'],guarantees:['Selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'ELV-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'EQUIPEMENT',name:'Crédit équipement',family:'Investissement',profiles:['Entrepreneur individuel','Personne morale','Groupe / Coopérative'],minAmount:100000,maxAmount:25000000,minMonths:6,maxMonths:48,periodicities:['Mensuelle','Trimestrielle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité / document légal','Devis ou justificatif équipement','Preuves de capacité'],guarantees:['Équipement financé et/ou autre selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'EQP-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'HABITAT',name:'Crédit habitat',family:'Habitat',profiles:['Personne physique'],minAmount:250000,maxAmount:25000000,minMonths:6,maxMonths:60,periodicities:['Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité','Justificatifs revenus','Justificatifs du projet habitat'],guarantees:['Selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'HAB-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'SOCIAL',name:'Crédit social / consommation',family:'Social',profiles:['Personne physique'],minAmount:50000,maxAmount:3000000,minMonths:1,maxMonths:24,periodicities:['Mensuelle'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Pièce d’identité','Justificatifs revenus','Justificatif objet si requis'],guarantees:['Selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'SOC-1.0',status:'ACTIF',source:'Famille de produit configurable'},
 {code:'GROUPEMENT',name:'Crédit groupement / coopérative',family:'Groupe / Coopérative',profiles:['Groupe / Coopérative'],minAmount:250000,maxAmount:25000000,minMonths:3,maxMonths:36,periodicities:['Mensuelle','Trimestrielle','Saisonnière'],rate:{type:'ANNUEL',value:18,method:'Dégressif'},defermentMonths:0,requiredDocs:['Documents légaux du groupement','PV/autorisation','Preuves activité et flux'],guarantees:['Selon politique'],workflow:['AGENT_CREDIT','ANALYSTE_RESPONSABLE_CREDIT','COMITE_CREDIT'],policyVersion:'GRP-1.0',status:'ACTIF',source:'Famille de produit configurable'}
];
export function ensureCatalog(db){db.creditProducts??=clone(DEFAULT_PRODUCTS);db.productPolicyVersions??=[];for(const p of db.creditProducts){if(!db.productPolicyVersions.some(v=>v.productCode===p.code&&v.version===p.policyVersion))db.productPolicyVersions.push({productCode:p.code,version:p.policyVersion,status:'PUBLIÉE',publishedAt:'2026-09-22T00:00:00.000Z',snapshot:clone(p)})}return db}
export function activeProducts(db){ensureCatalog(db);return db.creditProducts.filter(p=>p.status==='ACTIF')}
export function productByName(db,name){return activeProducts(db).find(p=>p.name===name)||activeProducts(db).find(p=>p.code===name)||null}
export function validateProductRequest(db,{product,amount,requestedAmount,durationMonths,periodicity,memberType}){const p=productByName(db,product);if(!p)return {ok:false,errors:['Produit de crédit inactif ou inconnu']};const errors=[];amount=Number(amount??requestedAmount)||0;durationMonths=Number(durationMonths)||0;if(amount<p.minAmount||amount>p.maxAmount)errors.push(`Montant hors limites (${p.minAmount}–${p.maxAmount})`);if(durationMonths<p.minMonths||durationMonths>p.maxMonths)errors.push(`Durée hors limites (${p.minMonths}–${p.maxMonths} mois)`);if(!p.periodicities.includes(periodicity))errors.push('Périodicité non autorisée pour ce produit');if(memberType&&!p.profiles.includes(memberType))errors.push('Profil membre non éligible à ce produit');return {ok:errors.length===0,errors,product:p}}
export function freezePolicySnapshot(db,application){const p=productByName(db,application.product);if(!p)return null;application.productCode=p.code;application.policyVersion=p.policyVersion;application.productPolicySnapshot=clone(p);return application.productPolicySnapshot}
export function upsertProduct(db,input,actor='Administrateur Système'){ensureCatalog(db);const code=String(input.code||'').trim().toUpperCase();if(!code)throw Error('Code produit obligatoire');let p=db.creditProducts.find(x=>x.code===code);const data={...input,code,name:String(input.name||'').trim(),minAmount:Number(input.minAmount)||0,maxAmount:Number(input.maxAmount)||0,minMonths:Number(input.minMonths)||1,maxMonths:Number(input.maxMonths)||1,status:input.status||'BROUILLON',updatedAt:new Date().toISOString(),updatedBy:actor};if(p)Object.assign(p,data);else db.creditProducts.push(p=data);return p}
export function publishProductPolicy(db,code,actor='Administrateur Système'){ensureCatalog(db);const p=db.creditProducts.find(x=>x.code===code);if(!p)throw Error('Produit introuvable');const base=(Number(String(p.policyVersion||'0').split('-').at(-1))||0)+1;p.policyVersion=`${code}-${base}.0`;p.status='ACTIF';db.productPolicyVersions.push({productCode:code,version:p.policyVersion,status:'PUBLIÉE',publishedAt:new Date().toISOString(),publishedBy:actor,snapshot:clone(p)});return p}
