const td=new TextDecoder();
function u16(d,o){return d[o]|d[o+1]<<8} function u32(d,o){return (d[o]|d[o+1]<<8|d[o+2]<<16|d[o+3]<<24)>>>0}
async function inflate(bytes){if(typeof DecompressionStream==='undefined')throw Error('Décompression XLSX indisponible dans ce navigateur');const s=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));return new Uint8Array(await new Response(s).arrayBuffer())}
async function unzip(buffer){const d=new Uint8Array(buffer),files={};let e=d.length-22;while(e>=0&&u32(d,e)!==0x06054b50)e--;if(e<0)throw Error('Fichier XLSX/ZIP invalide');let n=u16(d,e+10),p=u32(d,e+16);for(let i=0;i<n;i++){if(u32(d,p)!==0x02014b50)break;const method=u16(d,p+10),cs=u32(d,p+20),nl=u16(d,p+28),xl=u16(d,p+30),cl=u16(d,p+32),lo=u32(d,p+42),name=td.decode(d.slice(p+46,p+46+nl));const lnl=u16(d,lo+26),lxl=u16(d,lo+28),start=lo+30+lnl+lxl,raw=d.slice(start,start+cs);files[name]=method===0?raw:method===8?await inflate(raw):null;p+=46+nl+xl+cl}return files}
const ent=s=>String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
function strings(xml){return [...xml.matchAll(/<(?:\w+:)?si[\s\S]*?<\/(?:\w+:)?si>/g)].map(m=>ent([...m[0].matchAll(/<(?:\w+:)?t[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g)].map(x=>x[1]).join('')))}
function rows(xml,ss){const out=[];for(const rm of xml.matchAll(/<(?:\w+:)?row[^>]*>([\s\S]*?)<\/(?:\w+:)?row>/g)){const row={};for(const cm of rm[1].matchAll(/<(?:\w+:)?c\s+([^>]*)>([\s\S]*?)<\/(?:\w+:)?c>/g)){const attrs=cm[1],body=cm[2],ref=(attrs.match(/r="([A-Z]+)\d+"/)||[])[1],type=(attrs.match(/t="([^"]+)"/)||[])[1],v=(body.match(/<(?:\w+:)?v>([\s\S]*?)<\/(?:\w+:)?v>/)||[])[1]??'',inline=(body.match(/<(?:\w+:)?t[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/)||[])[1];if(ref)row[ref]=type==='s'?ss[Number(v)]??'':type==='inlineStr'?ent(inline):ent(v)}out.push(row)}return out}
const col=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s}
function objects(rs){if(!rs.length)return[];const head=rs[0],keys=Object.keys(head).sort((a,b)=>a.length-b.length||a.localeCompare(b)).map(c=>String(head[c]||c).trim());return rs.slice(1).filter(r=>Object.values(r).some(v=>String(v).trim())).map(r=>Object.fromEntries(keys.map((k,i)=>[k,r[col(i)]??''])))}
export async function parseCredipassWorkbook(file){const files=await unzip(await file.arrayBuffer()),ss=files['xl/sharedStrings.xml']?strings(td.decode(files['xl/sharedStrings.xml'])):[];const sheet=n=>files[`xl/worksheets/sheet${n}.xml`]?objects(rows(td.decode(files[`xl/worksheets/sheet${n}.xml`]),ss)):[];return {members:sheet(1),applications:sheet(2),sheets:Object.keys(files).filter(x=>x.startsWith('xl/worksheets/sheet')).length}}
