export const FINANCIAL_LEARNING_CATALOG = [
  {id:'LEARN-CREDIT-COST',priorityBase:2,minutes:12,titleFr:'Comprendre le coût réel d’un crédit',titleEn:'Understand the true cost of credit',objectiveFr:'Distinguer capital, intérêts, frais, assurance et coût total avant de signer.',objectiveEn:'Distinguish principal, interest, fees, insurance and total cost before signing.',triggers:['always'],format:'micro-course'},
  {id:'LEARN-SALES-RECORDS',priorityBase:1,minutes:15,titleFr:'Transformer les ventes quotidiennes en preuves financières',titleEn:'Turn daily sales into financial evidence',objectiveFr:'Tenir un registre simple, rapprocher les reçus et éviter les doubles comptages.',objectiveEn:'Keep a simple ledger, reconcile receipts and avoid double counting.',triggers:['low-confidence','short-history','cashflow-volatility'],format:'guided-practice'},
  {id:'LEARN-DEBT-MAP',priorityBase:1,minutes:14,titleFr:'Cartographier toutes ses dettes avant un nouveau crédit',titleEn:'Map all debts before taking new credit',objectiveFr:'Lister créanciers, mensualités, échéances et dettes contestées pour prévenir le surendettement.',objectiveEn:'List creditors, installments, maturities and disputed debts to prevent over-indebtedness.',triggers:['debt-risk','debt-mismatch','multiple-debt'],format:'guided-practice'},
  {id:'LEARN-SAVINGS-BUFFER',priorityBase:2,minutes:10,titleFr:'Construire un coussin d’épargne de sécurité',titleEn:'Build a safety savings buffer',objectiveFr:'Définir une réserve adaptée aux charges essentielles et aux périodes faibles.',objectiveEn:'Set a reserve aligned with essential expenses and weak periods.',triggers:['low-savings','fragile-health'],format:'micro-course'},
  {id:'LEARN-SEASONAL-PLAN',priorityBase:1,minutes:16,titleFr:'Planifier un crédit selon les saisons de l’activité',titleEn:'Plan credit around business seasons',objectiveFr:'Aligner décaissement, différé et remboursements sur les cycles réels de revenus.',objectiveEn:'Align disbursement, grace and repayments with real income cycles.',triggers:['seasonal'],format:'scenario'},
  {id:'LEARN-CONSENT-DATA',priorityBase:2,minutes:8,titleFr:'Contrôler le partage de ses données financières',titleEn:'Control sharing of financial data',objectiveFr:'Comprendre consentement, durée, révocation et minimisation des données.',objectiveEn:'Understand consent, duration, revocation and data minimization.',triggers:['always'],format:'micro-course'},
  {id:'LEARN-COOP-GOVERNANCE',priorityBase:1,minutes:18,titleFr:'Financement collectif et responsabilité limitée',titleEn:'Collective financing and limited liability',objectiveFr:'Comprendre gouvernance, consentement individuel, garanties plafonnées et suivi collectif.',objectiveEn:'Understand governance, individual consent, capped guarantees and collective monitoring.',triggers:['cooperative'],format:'scenario'},
  {id:'LEARN-EARLY-WARNING',priorityBase:2,minutes:10,titleFr:'Réagir tôt avant qu’un retard ne devienne un impayé',titleEn:'Act early before a delay becomes arrears',objectiveFr:'Identifier les signaux faibles et demander un accompagnement avant la rupture de paiement.',objectiveEn:'Identify weak signals and seek support before payment breakdown.',triggers:['monitoring-alert'],format:'micro-course'}
];
