export const REPORTING_ENGINE_VERSION='2.9.0';
export const REPORT_TEMPLATES={
  committeePack:{id:'committeePack',order:1,audience:'creditCommittee',category:'decision',title:{fr:'Pack comité de crédit',en:'Credit committee pack'},description:{fr:'Synthèse décisionnelle : données, confiance, INCLUSCORE, capacité, dette, simulation, règles et décision humaine.',en:'Decision summary: data, confidence, INCLUSCORE, capacity, debt, simulation, rules and human decision.'}},
  incluscore:{id:'incluscore',order:2,audience:'creditAnalyst',category:'risk',title:{fr:'Rapport INCLUSCORE explicable',en:'Explainable INCLUSCORE report'},description:{fr:'Score, sous-scores, facteurs, données utilisées, exclusions, incertitudes et versions.',en:'Score, sub-scores, factors, used data, exclusions, uncertainties and versions.'}},
  dataConfidence:{id:'dataConfidence',order:3,audience:'creditAnalyst',category:'data',title:{fr:'Rapport de confiance des données',en:'Data confidence report'},description:{fr:'Complétude, fraîcheur, vérification, diversité, cohérence, couverture et traçabilité.',en:'Completeness, freshness, verification, diversity, coherence, coverage and traceability.'}},
  financialHealth:{id:'financialHealth',order:4,audience:'creditAnalyst',category:'finance',title:{fr:'Diagnostic de santé financière',en:'Financial health diagnostic'},description:{fr:'Reste à vivre, capacité prudente, taux d’effort, épargne et résistance aux chocs.',en:'Rest-to-live, prudent capacity, commitment ratios, savings and stress resilience.'}},
  debt:{id:'debt',order:5,audience:'creditAnalyst',category:'finance',title:{fr:'Rapport dette et surendettement',en:'Debt and over-indebtedness report'},description:{fr:'Engagements consolidés, rapprochements, alertes et risque de surendettement.',en:'Consolidated commitments, reconciliation, alerts and over-indebtedness risk.'}},
  simulation:{id:'simulation',order:6,audience:'creditCommittee',category:'decision',title:{fr:'Simulation de crédit responsable',en:'Responsible credit simulation'},description:{fr:'Montant, durée, coûts, échéancier et stress tests, sans décision automatique.',en:'Amount, duration, costs, schedule and stress tests, without automatic decision.'}},
  humanDecision:{id:'humanDecision',order:7,audience:'creditCommittee',category:'decision',title:{fr:'Décision humaine motivée',en:'Reasoned human decision'},description:{fr:'Recommandation initiale, décision, dérogation, seconde revue et droit de recours.',en:'Initial recommendation, decision, override, second review and appeal right.'}},
  progression:{id:'progression',order:8,audience:'beneficiary',category:'support',title:{fr:'Plan d’amélioration financière',en:'Financial improvement plan'},description:{fr:'Actions 30/60/90 jours, objectifs mesurables et projections non garanties.',en:'30/60/90-day actions, measurable targets and non-guaranteed projections.'}},
  monitoring:{id:'monitoring',order:9,audience:'supervisor',category:'monitoring',title:{fr:'Rapport de suivi après financement',en:'Post-financing monitoring report'},description:{fr:'Échéances, revenus observés, alertes précoces et interventions humaines.',en:'Installments, observed income, early warnings and human interventions.'}},
  coopScore:{id:'coopScore',order:10,audience:'creditCommittee',category:'cooperative',title:{fr:'Rapport COOP-SCORE',en:'COOP-SCORE report'},description:{fr:'Gouvernance, cotisations, remboursement interne, capacité, résilience et concentration.',en:'Governance, contributions, internal repayment, capacity, resilience and concentration.'}},
  groupFinancing:{id:'groupFinancing',order:11,audience:'creditCommittee',category:'cooperative',title:{fr:'Rapport de financement collectif',en:'Group financing report'},description:{fr:'Consentements, responsabilités plafonnées, affectation, tranches et remboursement.',en:'Consents, capped responsibilities, allocations, tranches and repayment.'}},
  portfolioRisk:{id:'portfolioRisk',order:12,audience:'riskDirector',category:'portfolio',title:{fr:'Rapport de risque portefeuille',en:'Portfolio risk report'},description:{fr:'PAR, concentrations, expositions, scénarios de stress et dossiers à revoir.',en:'PAR, concentrations, exposures, stress scenarios and files to review.'}},
  institutionalPilot:{id:'institutionalPilot',order:13,audience:'executive',category:'institution',title:{fr:'Rapport institutionnel',en:'Institutional assessment report'},description:{fr:'Readiness, ROI illustratif, configuration, sécurité et plan de déploiement sur 90 jours.',en:'Readiness, illustrative ROI, configuration, security and 90-day deployment plan.'}},
  verification:{id:'verification',order:14,audience:'riskDirector',category:'verification',title:{fr:'Rapport de vérification et anomalies',en:'Verification and anomaly report'},description:{fr:'Signaux, priorités de vérification, dispositions humaines et garde-fous anti-faux positifs.',en:'Signals, verification priorities, human dispositions and false-positive safeguards.'}},
  fieldOperations:{id:'fieldOperations',order:15,audience:'supervisor',category:'field',title:{fr:'Rapport terrain et synchronisation',en:'Field and synchronization report'},description:{fr:'Missions, preuves collectées, files hors-ligne, conflits et synchronisation supervisée.',en:'Missions, captured evidence, offline queues, conflicts and supervised synchronization.'}}
};
export function listReportTemplates(){return Object.values(REPORT_TEMPLATES).sort((a,b)=>a.order-b.order);}
export function validateReportTemplates(){const ids=new Set();return listReportTemplates().every(t=>{if(!t.id||ids.has(t.id)||!t.title?.fr||!t.title?.en||!t.description?.fr||!t.description?.en)return false;ids.add(t.id);return true;});}
