import * as L from './modules/creditLedgerV2.js';
let db=L.load(), view='home', active=null; const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const money=n=>new Intl.NumberFormat('fr-FR').format(+n||0)+' FCFA';
const actor=()=>$('#userName')?.textContent||'Agent de crédit';
function persist(){L.save(db);render()}
function nav(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view))}
function render(){nav(); const root=$('#content'); try{root.innerHTML= view==='home'?home():view==='members'?members():view==='credits'?credits():view==='tasks'?tasks():view==='portfolio'?portfolio():view==='reports'?reports():view==='memberPortal'?memberPortal():view==='dossier'?dossierView():more()}catch(e){root.innerHTML=`<section class="panel error"><h2>Erreur</h2><p>${esc(e.message)}</p></section>`}}
function home(){const m=L.metrics(db);return `<div class="title"><div><span>Accueil</span><h2>Activité crédit</h2><p>Chaque indicateur provient des opérations enregistrées.</p></div><button data-act="newApp">＋ Nouvelle demande</button></div><div class="kpis">${[['Membres',m.members],['Demandes',m.applications],['En cours',m.inProgress],['Demandé',money(m.requested)],['Accordé',money(m.approved)],['Décaissé',money(m.disbursed)],['Encours',money(m.outstanding)]].map(x=>`<article><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('')}</div><section class="panel"><h3>Processus numérisé</h3><div class="flow">Membre → Demande → Constitution → Terrain → Analyse → Garanties → Décision → Décaissement → Remboursement → Suivi → Clôture</div></section>`}
function members(){return `<div class="title"><div><span>Membres</span><h2>Registre des membres</h2><p>Une fiche permanente, plusieurs demandes dans le temps.</p></div><button data-act="newMember">＋ Nouveau membre</button></div><section class="panel"><input id="memberSearch" placeholder="Nom, N° membre, téléphone, ville…"><div class="table"><table><thead><tr><th>N° membre</th><th>Nom</th><th>Type</th><th>Activité</th><th>Ville</th><th></th></tr></thead><tbody>${db.members.map(m=>`<tr data-search="${esc((m.memberNo+' '+m.name+' '+m.phone+' '+m.city).toLowerCase())}"><td>${esc(m.memberNo)}</td><td><b>${esc(m.name)}</b><br><small>${esc(m.phone)}</small></td><td>${esc(m.type)}</td><td>${esc(m.activity)}</td><td>${esc(m.city)}</td><td><button class="ghost" data-act="memberApps" data-id="${m.id}">Dossiers</button> <button class="ghost" data-act="editMember" data-id="${m.id}">Modifier</button></td></tr>`).join('')}</tbody></table></div></section>`}
function credits(filterMember=''){const list=db.applications.filter(a=>!filterMember||a.memberId===filterMember);return `<div class="title"><div><span>Crédits</span><h2>Demandes et crédits</h2><p>Le dossier suit le processus réel de crédit.</p></div><button data-act="newApp" ${filterMember?`data-member="${filterMember}"`:''}>＋ Nouvelle demande</button></div><section class="cards">${list.length?list.map(a=>{const m=db.members.find(x=>x.id===a.memberId),p=L.position(db,a.id);return `<article class="panel credit"><div><small>${a.id} · ${esc(a.status)}</small><h3>${esc(m?.name)}</h3><p>${esc(a.product)} · ${esc(a.purpose)}</p></div><div><b>${money(a.requestedAmount)}</b><small>${a.durationMonths} mois · ${esc(a.periodicity)}</small>${p.disbursed?`<small>Encours ${money(p.outstanding)}</small>`:''}</div><button data-act="open" data-id="${a.id}">Ouvrir →</button></article>`}).join(''):'<div class="panel">Aucun dossier.</div>'}</section>`}
function tasks(){const list=db.applications.filter(a=>!['REFUSÉ','CLÔTURÉ'].includes(a.status));return `<div class="title"><div><span>Tâches</span><h2>Travail à traiter</h2></div></div><section class="panel">${list.map(a=>`<div class="row"><span><b>${a.id}</b> · ${esc(db.members.find(m=>m.id===a.memberId)?.name)}</span><span>${esc(a.status)}</span><button class="ghost" data-act="open" data-id="${a.id}">Traiter</button></div>`).join('')}</section>`}
function portfolio(){const m=L.metrics(db);return `<div class="title"><div><span>Portefeuille</span><h2>Situation calculée</h2></div></div><div class="kpis">${[['Crédits décaissés',db.applications.filter(a=>L.position(db,a.id).disbursed>0).length],['Décaissé',money(m.disbursed)],['Principal remboursé',money(m.disbursed-m.outstanding)],['Encours',money(m.outstanding)]].map(x=>`<article><small>${x[0]}</small><strong>${x[1]}</strong></article>`).join('')}</div><section class="panel"><h3>Détail</h3>${db.applications.filter(a=>L.position(db,a.id).disbursed).map(a=>{const p=L.position(db,a.id);return `<div class="row"><span>${a.id} · ${esc(db.members.find(m=>m.id===a.memberId)?.name)}</span><span>Décaissé ${money(p.disbursed)}</span><b>Encours ${money(p.outstanding)}</b></div>`}).join('')||'Aucun crédit décaissé.'}</section>`}
function reports(){return `<div class="title"><div><span>Rapports</span><h2>Traçabilité</h2></div><button data-act="print">Imprimer / PDF</button></div><section class="panel"><h3>Journal d'audit</h3>${db.audit.slice(0,100).map(a=>`<div class="row"><small>${new Date(a.at).toLocaleString('fr-FR')}</small><b>${esc(a.action)}</b><span>${esc(a.actor)}</span></div>`).join('')}</section>`}
function more(){return `<div class="title"><div><span>Plus</span><h2>Administration</h2></div></div><section class="cards"><article class="panel"><h3>Espace membre</h3><p>Vue personnelle du membre : produits, demandes, suivi.</p><button data-nav="memberPortal">Ouvrir</button></article><article class="panel"><h3>Données</h3><p>Les données restent locales dans cette version offline-first.</p><button data-act="reset">Réinitialiser les données de test</button></article></section>`}
function memberPortal(){const m=db.members[0],apps=db.applications.filter(a=>a.memberId===m.id);return `<div class="title"><div><span>Espace membre</span><h2>Bonjour ${esc(m.name)}</h2><p>${esc(m.memberNo)} · ${esc(m.phone)}</p></div></div><div class="kpis"><article><small>Mes demandes</small><strong>${apps.length}</strong></article><article><small>Mes crédits actifs</small><strong>${apps.filter(a=>L.position(db,a.id).outstanding>0).length}</strong></article></div><section class="panel"><h3>Produits & services</h3><div class="row"><span>Crédit activité</span><span>Conditions communiquées par l'institution</span><button class="ghost" data-act="newApp" data-member="${m.id}">Demander</button></div></section><section class="panel"><h3>Mes demandes</h3>${apps.map(a=>`<div class="row"><span>${a.id} · ${esc(a.product)}</span><b>${esc(a.status)}</b><span>${money(a.requestedAmount)}</span></div>`).join('')||'Aucune demande.'}</section>`}
function dossierView(){if(!active)return credits();const d=L.dossier(db,active),a=d.application,m=d.member;const step=stage(a,d);return `<div class="title"><div><span>${a.id} · ${esc(a.status)}</span><h2>${esc(m.name)}</h2><p>${esc(a.product)} · ${money(a.requestedAmount)} · ${a.durationMonths} mois</p></div><button class="ghost" data-nav="credits">← Crédits</button></div><div class="steps">${['Demande','Constitution','Terrain','Analyse','Garanties','Décision','Décaissement','Suivi','Clôture'].map((s,i)=>`<span class="${i<=step?'done':''}">${i+1}. ${s}</span>`).join('')}</div><div class="workspace"><main>${dossierSections(d)}</main><aside class="panel summary"><h3>Synthèse</h3><div class="metric"><small>Capacité</small><strong>${money(d.financial.capacity)}</strong></div><div class="metric"><small>Garanties retenues</small><strong>${money(d.guarantees.reduce((s,g)=>s+(g.retainedValue||0),0))}</strong></div><div class="metric"><small>Décaissé</small><strong>${money(d.position.disbursed)}</strong></div><div class="metric"><small>Encours</small><strong>${money(d.position.outstanding)}</strong></div></aside></div>`}
function stage(a,d){if(a.status==='CLÔTURÉ')return 8;if(d.payments.length||a.status==='EN SUIVI')return 7;if(d.disbursements.length)return 6;if(d.decisions.length)return 5;if(d.guarantees.length)return 4;if(d.financials.length)return 3;if(d.visits.length)return 2;if(d.documents.length)return 1;return 0}
function dossierSections(d){const a=d.application;return `<section class="panel"><h3>1. Demande</h3><div class="row"><span>Objet</span><b>${esc(a.purpose||'—')}</b></div><div class="row"><span>Montant demandé</span><b>${money(a.requestedAmount)}</b></div><button data-act="editApp">Modifier la demande</button></section>
<section class="panel"><h3>2. Constitution / documents</h3>${d.documents.map(v=>`<div class="row"><span>${esc(v.label)}</span><b>${esc(v.status)}</b><small>${esc(v.source)}</small></div>`).join('')||'<p>Aucun document enregistré.</p>'}<button data-act="addDoc">＋ Ajouter un document</button></section>
<section class="panel"><h3>3. Vérification terrain</h3>${d.visits.map(v=>`<div class="row"><span>${new Date(v.at).toLocaleDateString('fr-FR')} · activité ${esc(v.activityObserved)}</span><small>${esc(v.observations)}</small></div>`).join('')||'<p>Aucune visite enregistrée.</p>'}<button data-act="addVisit">＋ Enregistrer une visite</button></section>
<section class="panel"><h3>4. Analyse économique</h3><div class="grid2"><div><small>Revenus / CA</small><b>${money(d.financial.revenue)}</b></div><div><small>Charges totales</small><b>${money(d.financial.expenses)}</b></div><div><small>Capacité calculée</small><b>${money(d.financial.capacity)}</b></div><div><small>Source</small><b>${esc(d.financial.source)}</b></div></div><button data-act="addFinancial">＋ Saisir / actualiser les flux</button></section>
<section class="panel"><h3>5. Garanties</h3>${d.guarantees.map(g=>`<div class="row"><span>${esc(g.type)} · ${esc(g.description)}</span><span>Déclarée ${money(g.declaredValue)}</span><b>Retenue ${g.retainedValue==null?'Non expertisée':money(g.retainedValue)}</b></div>`).join('')||'<p>Aucune garantie enregistrée.</p>'}<button data-act="addGuarantee">＋ Ajouter une garantie</button></section>
<section class="panel"><h3>6. Décision humaine</h3>${d.decisions.map(v=>`<div class="row"><span>${esc(v.decision)}</span><b>${money(v.approvedAmount)}</b><small>${esc(v.reason)}</small></div>`).join('')||'<p>Aucune décision enregistrée.</p>'}<button data-act="decision">Enregistrer la décision</button></section>
<section class="panel"><h3>7. Décaissement</h3>${d.disbursements.map(v=>`<div class="row"><span>${new Date(v.at).toLocaleDateString('fr-FR')} · ${esc(v.method)}</span><b>${money(v.amount)}</b><small>${esc(v.reference)}</small></div>`).join('')||'<p>Aucun décaissement.</p>'}<button data-act="disburse">＋ Enregistrer un décaissement</button></section>
<section class="panel"><h3>8. Suivi / remboursements</h3>${d.payments.map(v=>`<div class="row"><span>${new Date(v.at).toLocaleDateString('fr-FR')} · ${esc(v.method)}</span><b>${money(v.amount)}</b><small>Principal ${money(v.principal)} · Intérêt ${money(v.interest)}</small></div>`).join('')||'<p>Aucun remboursement.</p>'}<div class="actions"><button data-act="payment">＋ Enregistrer un paiement</button><button class="ghost" data-act="restructure">Restructuration</button></div>${d.restructures.map(v=>`<div class="notice">Restructuration : ${esc(v.reason)} · ${v.newDuration} mois</div>`).join('')}</section>
<section class="panel"><h3>9. Clôture</h3><p>La clôture n'est autorisée que lorsque l'encours est nul.</p><button data-act="close">Clôturer le crédit</button></section>`}
function modal(title,fields,onSubmit){const dlg=$('#modal');dlg.innerHTML=`<form method="dialog"><header><h3>${title}</h3><button value="cancel" class="ghost">×</button></header><div class="form">${fields}</div><footer><button value="cancel" class="ghost">Annuler</button><button id="saveModal" value="default">Enregistrer</button></footer></form>`;dlg.showModal();$('#saveModal').onclick=e=>{e.preventDefault();const f=new FormData(dlg.querySelector('form'));try{onSubmit(Object.fromEntries(f.entries()));L.save(db);dlg.close();render()}catch(err){alert(err.message)}}}
const input=(n,l,t='text',v='')=>`<label>${l}<input name="${n}" type="${t}" value="${esc(v)}"></label>`; const select=(n,l,opts,v='')=>`<label>${l}<select name="${n}">${opts.map(o=>`<option ${o===v?'selected':''}>${esc(o)}</option>`).join('')}</select></label>`;
function act(name,el){if(name==='newMember')return modal('Nouveau membre',select('type','Type de membre',L.TYPES)+input('name','Nom / raison sociale')+input('memberNo','N° membre')+input('phone','Téléphone')+input('city','Ville')+input('activity','Activité'),d=>L.addMember(db,d,actor()));if(name==='editMember'){const m=db.members.find(x=>x.id===el.dataset.id);return modal('Modifier le membre',select('type','Type',L.TYPES,m.type)+input('name','Nom', 'text',m.name)+input('memberNo','N° membre','text',m.memberNo)+input('phone','Téléphone','text',m.phone)+input('city','Ville','text',m.city)+input('activity','Activité','text',m.activity),d=>L.updateMember(db,m.id,d,actor()))}if(name==='memberApps'){view='credits';$('#content').innerHTML=credits(el.dataset.id);return}
if(name==='print')return print();if(name==='reset'){if(confirm('Réinitialiser les données locales ?')){db=L.seed();persist()}return}
if(name==='newApp'){const member=el.dataset.member||db.members[0]?.id;return modal('Nouvelle demande',select('memberId','Membre',db.members.map(m=>m.id),member)+input('product','Produit','text','Crédit activité')+input('purpose','Objet')+input('requestedAmount','Montant demandé','number')+input('durationMonths','Durée (mois)','number','12')+select('periodicity','Périodicité',['Mensuelle','Hebdomadaire','Trimestrielle','Saisonnière']),d=>{const a=L.addApplication(db,d,actor());active=a.id;view='dossier'})}if(name==='open'){active=el.dataset.id;view='dossier';return render()}if(!active)return;
const d=L.dossier(db,active),a=d.application;
if(name==='editApp')return modal('Modifier la demande',input('product','Produit','text',a.product)+input('purpose','Objet','text',a.purpose)+input('requestedAmount','Montant','number',a.requestedAmount)+input('durationMonths','Durée','number',a.durationMonths)+select('periodicity','Périodicité',['Mensuelle','Hebdomadaire','Trimestrielle','Saisonnière'],a.periodicity),x=>L.updateApplication(db,active,x,actor()));
if(name==='addDoc')return modal('Ajouter un document',input('label','Document')+select('status','Statut',['Reçu','À vérifier','Vérifié','Rejeté','Expiré'])+select('source','Source',['Documenté','Déclaré','Observé'])+input('reference','Référence'),x=>L.addDocument(db,{...x,applicationId:active},actor()));
if(name==='addVisit')return modal('Visite terrain',select('addressVerified','Adresse vérifiée',['Oui','Non','Partiellement'])+select('activityObserved','Activité observée',['Oui','Non','Partiellement'])+input('stock','Stock observé')+input('equipment','Équipements observés')+`<label>Observations<textarea name="observations"></textarea></label>`,x=>L.addVisit(db,{...x,applicationId:active},actor()));
if(name==='addFinancial')return modal('Analyse économique',input('revenue','Revenus / CA','number',d.financial.revenue)+input('businessExpenses','Charges activité','number',d.financial.businessExpenses||0)+input('householdExpenses','Charges ménage','number',d.financial.householdExpenses||0)+input('debtPayments','Autres échéances','number',d.financial.debtPayments||0)+select('source','Source',['Déclaré','Documenté','Observé','Reconstitué','Déclaré + documenté']),x=>L.addFinancial(db,{...x,applicationId:active},actor()));
if(name==='addGuarantee')return modal('Garantie',input('type','Type','text','Matériel')+input('description','Description')+input('owner','Propriétaire')+input('declaredValue','Valeur déclarée','number')+input('expertValue','Valeur expertisée','number')+input('retainedValue','Valeur retenue','number')+select('status','Statut',['À vérifier','Vérifiée','Expertisée','Rejetée']),x=>L.addGuarantee(db,{...x,applicationId:active},actor()));
if(name==='decision')return modal('Décision',select('decision','Décision',['VALIDÉ','AJOURNÉ','REFUSÉ'])+input('approvedAmount','Montant autorisé','number',a.requestedAmount)+`<label>Motif<textarea name="reason"></textarea></label><label>Conditions<textarea name="conditions"></textarea></label>`,x=>L.recordDecision(db,{...x,applicationId:active},actor()));
if(name==='disburse')return modal('Décaissement',input('amount','Montant','number')+select('method','Mode',['Caisse','Virement','Mobile Money'])+input('reference','Référence'),x=>L.disburse(db,{...x,applicationId:active},actor()));
if(name==='payment')return modal('Remboursement',input('amount','Montant payé','number')+input('interest','Part intérêts','number','0')+select('method','Mode',['Caisse','Virement','Mobile Money'])+input('reference','Référence'),x=>L.pay(db,{...x,applicationId:active},actor()));
if(name==='restructure')return modal('Restructuration / rééchelonnement',`<label>Cause<textarea name="reason"></textarea></label>`+input('evidence','Preuve / référence')+input('newDuration','Nouvelle durée','number',a.durationMonths)+select('newPeriodicity','Nouvelle périodicité',['Mensuelle','Hebdomadaire','Trimestrielle','Saisonnière'],a.periodicity),x=>L.restructure(db,{...x,applicationId:active},actor()));
if(name==='close'){try{L.close(db,active,actor());persist()}catch(e){alert(e.message)}return}
}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){view=n.dataset.nav;active=null;render();return}const a=e.target.closest('[data-act]');if(a)act(a.dataset.act,a)});document.addEventListener('input',e=>{if(e.target.id==='memberSearch'){const q=e.target.value.toLowerCase();document.querySelectorAll('tr[data-search]').forEach(r=>r.hidden=!r.dataset.search.includes(q))}});window.addEventListener('error',e=>{$('#bootError').textContent='Erreur : '+e.message;$('#bootError').hidden=false});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
